### ISSUE TITLE
Support Arrays and Objects in the Service Descriptor Format

### ISSUE THREAD

**Issue by JordiPolo** [spotify/backstage#1083]
As per the discussion [here](https://github.com/spotify/backstage/issues/767) and the implementation [here](https://github.com/spotify/backstage/pull/894) inside `labels` and `annotations` we have a series of key-values where values must be strings.

This is very limiting.

For instance, in the original issue @freben talks of the dangers of not being specific with the roles of the people mentioned in this file. On that theme, I'd love to do this:
```yaml
contacts:
  - role: architect
     name: John Smith
     email: js@yyy.com
  - role: engineer
     name: hacker1
     email: h1@yyy.com
  - role: engineer
     name: hacker2
     email: h2@yyy.com
```
The shape here would be well defined, you need `role`, `name` and `email` per each contact but role can be anything that makes sense to you so this is pretty flexible.

With the current limitations I'd need to do something like:
```yaml
engineers: "hacker1:h1@yyy.com;hacker2:h2@yyy.com"
```
Or any other random serialization of the above information into the key and the string value. Pretty unreadable which I believe is contrary to the goal of the format.

One could find many other applications of objects and/or arrays. For instance:
```yaml
team:
  name:
  email:
  slack_channel:
```
Etc.

The only reason I can think of to stay with strings is that it is straightforward to use them as environment variables, but is there a use-case for that?

@Rugvip @freben @nikek  FYI.

**Comment by freben** [comment]
Hi!

## Context

The background for making these strings in the first place, is that that perfectly matches the kubernetes object model. So we follow both the format and, perhaps more importantly, the semantics set in place by that standard, and have been hesitant to stray away from that without good reason.

## Alternatives

These format policies only apply to labels and annotations. The reason is that they are normally used for very specific things. The labels are the most apparent; they will be used for subselection/filtering within the catalog, and sometimes even exposed in the user interface in dropdowns etc. So those you may not want to change. Annotations are more liberal. One thing that has been suggested is to either break it up into several annotations:

```
contact.architect.name: John Smith
contact.architect.email: js@yyy.com
```

Or to store it as yaml in a literal:

```
contact.architect: |
  name: John Smith
  email: js@yyy.com
```

(notice the `|`)

Admittedly these are a bit kludgy.

What you can also consider is whether the information you want actually could belong elsewhere, not in labels or annotations - could it be that wou want a field `metadata.contact` instead, or even `spec.contact`? Probably the former, if so. We are open to discussion, and if these use cases emerge a lot we may want to cement them into the standard as well so that other plugins can consume it consistently.

## (Advanced)

Now having said all that, the catalog backend itself is actually not locked into these particular policies. It will store the entire metadata blob as generic JSON no matter what. The thing that places restrictions on entities entering the system is [this policy](https://github.com/spotify/backstage/blob/master/packages/catalog-model/src/entity/policies/FieldFormatEntityPolicy.ts), governed by [these field validators](https://github.com/spotify/backstage/blob/master/packages/catalog-model/src/validation/makeValidator.ts). You can see things being wired together [here in the example backend](https://github.com/spotify/backstage/blob/master/packages/backend/src/plugins/catalog.ts). Both can be swapped out, so you can either use the builtin policy with your own more permissive field format validators, or just throw out the policy entirely and write your own.

This should only be done as a last resort and probably after discussing things together, because there will likely be a lot of plugins that interact with the entity model and they may not be expecting to get data on other shapes than the standard one. So you run the risk of becoming less compatible with the rest of the ecosystem.

**Comment by JordiPolo** [comment]
Thanks so much for the throughout response.
I was not aware that `metadata` is open to adding more keys. I need to re-read the ADR with more care it may seem.

It is great news as this would open it up for any experimentation different groups may need.
I like your approach of letting people play with the format and only consolidating when there is proven real-world usage.
That said, I am pretty certain a need will arise to relate components to people in flexible ways but we can discuss that in some other issue.

I am closing this one as arrays and objects are allowed within custom keys within `metadata`.

By the way, reading the policy code, I'd suggest you consider creating a json schema for this format and validating the file format by applying that json schema. This way the format will be less ambiguous and at the same time you get rid of some code, you delegate that to some json-schema library.

**Comment by Rugvip** [comment]
@JordiPolo If I understand you correctly we have an open issue for the json schema bit! https://github.com/spotify/backstage/issues/843, you up? :grin:

**Comment by JordiPolo** [comment]
I do not know enough of Typescript to not do a disaster but a json schema, I can do that. I'll try to get something this week.

**Comment by freben** [comment]
Cool! I think we'll have to have a common minimum base structure though, because otherwise entities won't be usable by any other plugin. So maybe you could express one json schema that's similar to the DEFAULT_ENTITY_SCHEMA except `labels` and `annotations` are effectively `Record<string, any>` instead? Then a second level validator (or a subschema that gets passed into the larger schema, if that's a thing) can apply further strictness rules on top of that.

There are a few rules that may not lend themselves as well to plain schema validation, such as the ReservedFieldsEntityPolicy, but let's see what you come up with.

**Comment by JordiPolo** [comment]
Questions:
- In the ADR the values of labels and annotations are explicitly said to the strings. Why the change to `any` in the schema? And what are the possible types for `any`? 

- Why you think we would need a second more strict schema?

I think ReservedFieldsEntityPolicy is pointing to a problem in the design of the format. It is not only about these particular reserved fields, at any moment a future version of the format could add a new not-reserved key which could conflict with my custom keys confusing plugins. I do not think it is a good idea to use the same namespace for custom and official keys.

**Comment by freben** [comment]
Oh I was probably being unclear.

I understood there was a need to have a flexible typing for annotation values. That some orgs might choose to put other types of value there, not just strings.

At the same time, I want there to be as much structure as possible, that everybody globally can rely on, so that they can easily parse and semantically understand entities. And the default should still be to have string annotation values just like today.

Given those two constraints, I had the hypothesis that maybe a split of the schema would be one possible solution. We could either:

- Have a SchemaValidEntityPolicy (uses json schema) that takes a constructor parameter: a sub-json-schema for entity values (if none is given, the default is to work like today)

or

- Have a SchemaValidEntityPolicy that permits any annotation value (uses json schema), followed by a separate AnnotationValueEntityPolicy that does nothing but apply some rule to annotation values where present.

or

- Keep everything as it is today, and just pass a custom [isValidAnnotationValue](https://github.com/spotify/backstage/blob/master/packages/catalog-model/src/validation/makeValidator.ts#L30) :)

Does that make sense? Either way, I want that there should be no extra effort to make things work like they do today.

**Comment by JordiPolo** [comment]
Just to be cristal clear, from the first response my assumption is that the following would be legal:
```yaml
apiVersion: backstage.io/v1beta1
kind: Component
spec:
  type: service
metadata:
  name: LoremService
  description: Creates Lorems like a pro.
  labels:
    product_name: "Random value generator, buy it now"
  teams:
    - name: "Team super great"
      email: greatTeam@mdsol.com 
  annotations:
    docs: https://github.com/..../tree/develop/doc
```

Where values for `labels` and `annotations` are strings. 
Inside `metadata` I can add whatever else I need, in this case a list of teams involved in this project.

This is Good Enough™ for a beta1 to me, with the caveat of adding keys may conflict with custom keys in the future. 
This would be simple to express in Json Schema including the types allowed and more fancy stuff like if you want some limits on the length of the name or the labels or anything. Also can express the limitations of what especial characters are allowed in values.

I can do this and I think that will let you remove your hand-crafted validation.

If you want me to change the above in any way, whatever you tell me. I'd recommend you to keep it strict if possible though, I think it would make coding easier for you.

**Comment by freben** [comment]
You understood that right! If you are fine with leaving the label/annotation semantics as-is, then by all means go ahead and skip making them flexible. If that ever becomes a strict demand, we can always add that flexibility later.
