### ISSUE TITLE
Show signed in user's name

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#1356]
## Feature Suggestion

Replace the "friend" with the signed in user's (first) name or "guest" if the user is not signed in.

![Screenshot 2020-06-17 at 21 35 54](https://user-images.githubusercontent.com/190856/84942079-9c52f000-b0e2-11ea-95cd-f05df8ea8881.png)

## Possible Implementation

Use the new Auth API. Perhaps @Rugvip or @soapraj can point to docs/reference?

## Context

Backstage should feel like home and should be as personal and welcoming as possible.

**Comment by daniel-j-davis** [comment]
I'd like to take this on, @stefanalund. Any documentation or somewhere I can reference the auth API? I'll dig through the source in the meantime.

**Comment by stefanalund** [comment]
@daniel-j-davis awesome, I'm assigning you then. The existing auth docs can be found here: https://github.com/spotify/backstage/tree/master/docs/auth

**Comment by Rugvip** [comment]
We don't have a display name or anything like that quite yet btw, so probably best to use the userId from the [IdentityApi](https://github.com/spotify/backstage/blob/master/packages/core-api/src/apis/definitions/IdentityApi.ts) for now.

**Comment by daniel-j-davis** [comment]
OK, cool. I spent some time looking through the source and familiarizing myself with everything, but ran into an issue logging in locally and haven't had the time to look into it yet. I'm guessing it's probably because I need to set a client id and secret for local auth, but going to look into that soon and start on this issue. Should be fairly straight forward once I get my local environment set up!

**Comment by Rugvip** [comment]
Yep, if you wanna try out Google auth already, you'll have to set up an OAuth app in GCP. Although tbh using the guest or custom login options for development is gonna work just fine too. Once you're in the app they're functionally identical.

**Comment by daniel-j-davis** [comment]
Yeah, I just figured out that it's fine to use `Custom User` and plug my own user id in to test, thanks! Is it by design that `hasIdentity` is true, even if the user is logged in as a guest? I'm wondering whether or not it's fine to just always show whatever `getUserId()` returns because that seems to return `guest` when they're a guest, which is what the string should say for those who don't actually have any other name/identity, but want to make sure that's the expected behaviour.

**Comment by Rugvip** [comment]
Yeah `hasIdentity` is just an internal flag that keeps track of whether the sign-in is complete, so even guest counts as an identity in that sense. And yeah using `getUserId()` would be what we want right now. 👍
