### ISSUE TITLE
Don't require JSON encoding of config values supplied through env.

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1765]
## Feature Suggestion

When supplying a config value through an env var it currently needs to be JSON-encoded, e.g.

```
APP_CONFIG_app_baseUrl='"http://localhost:3001"'
```

Let's remove that requirement by falling back to assuming the value is a string if it fails `JSON.parse`.

## Possible Implementation

It needs to be implemented in all places where env-vars are read, which is currently [here](https://github.com/spotify/backstage/blob/db5e0408cbbfdac9997fd257458578d698ecb218/packages/config-loader/src/lib/env.ts#L75) and [here](https://github.com/spotify/backstage/blob/db5e0408cbbfdac9997fd257458578d698ecb218/docker/run.sh#L19). If the parsing fails we simply fall back to using the value as-is.

## Context

Multiple requests for this feature on Discord, along with some deployment environments not allowing the JSON-encoding to be passed through at all.

**Comment by andrewthauer** [comment]
I can take this one

**Comment by Rugvip** [comment]
@andrewthauer Thanks! 😁

**Comment by andrewthauer** [comment]
So the easy solution would be to just always fallback to a string value. However, this will make the majority of the current tests obsolete since everything is a string in `process.env` by default. It also will not catch situations where the value was intended to be an actual json object but has a syntax error. Are we ok with losing those checks? Other options could be to try to infer the intended type (which could be complicated) or just log something when it falls back to a string.
