### ISSUE TITLE
Invalid host header error

### ISSUE THREAD

**Issue by nnganesha** [spotify/backstage#1821]
I installed this on an Amazon AWS VM (Ubuntu). Following are the changes I made.

Updated app-config.yml to change baseUrl (under app section) to http://0.0.0.0:3000, so that all addresses can bind to it. It is working fine outside as well, as long as I use the url http://ipaddress:3000/. But when I access this via AWS Loadbalancer, where I give a specific DNS name, such as https://backstage.mycompany.com, by creating target group and routing via app load balancer, I am getting an error "Invalid host header". Any suggestions?

**Comment by Rugvip** [comment]
Afaik the following config should allow things to work:

```yaml
backend:
  listen: 0.0.0.0:3000
  baseUrl: https://backstage.mycompany.com

...
```

**Comment by nnganesha** [comment]
Do I need to change for Backend section as well? I thought I just need to change app section...

**Comment by Rugvip** [comment]
@nnganesha Ah was assuming it was the `backend` section, sorry.

In the app section it should be fine to just use `baseUrl: https://backstage.mycompany.com`. If you're using the nginx docker container it should always be binding to just 80, so you get to map that as you please in the docker port bindings. If you're not using the standard container it'll be up to you to set up serving of the static content.

**Comment by nnganesha** [comment]
sure no problems.. thanks for the reply. but i just did a git clone and did a yarn install & yarn start.. It brings up the portal on 3000 by default. I can access from other machines as well if I access via ip address. But when I access via aws load balancer, this error pops up. Is there a way I can disable host check via any command line switches in the yarn start statement?

**Comment by Rugvip** [comment]
`yarn start` is really just for local development. For serving the app even in a demo setup you'll want to build a dist version of the app with `yarn build`. You can then use any simple static http server, like https://www.npmjs.com/package/http-server, to serve the contents of `packages/app/dist`.

Alternatively if you want to hack it together anyway, you could head to your local https://github.com/spotify/backstage/blob/69c996408779b2db5fca043cfec08648c1617fb5/packages/cli/src/lib/bundler/server.ts#L40 and disable the host check since you have a clone.

**Comment by nnganesha** [comment]
Sure Patrik, thanks a lot for the suggestion. I will check and update you on this..

**Comment by nnganesha** [comment]
Thanks a lot Patrik, it worked very well.. I added below section in WebpackDevServer function, as suggested by you, at line number 42, as an additional parameter.. 

allowedHosts: [
      'backstage.mycompany.com',
      'mycompany.com',
      'localhost'
    ],

Many thanks for your inputs....

**Comment by Rugvip** [comment]
@nnganesha great! Alright with closing the issue?

**Comment by nnganesha** [comment]
yes please.. :)

**Comment by rbideau** [comment]
Hi,

I have the same problem with the _"Invalid host header"_ message.

I have my development environment in the cloud due to corporate policy but I don't run a fork of backstage, I've created an app.

Right now I monkey patch `node_modules/@backstage/cli/dist/csj/server-....cjs.js` ([source](https://github.com/backstage/backstage/blob/2837dec850f8d22b16d559127b7f1ef547e5cafd/packages/cli/src/lib/bundler/server.ts#L61)) to add in the WebpackDevServer options :
```typescript
  allowedHosts: [
    url.hostname,
  ],
```

But this is not ideal since the file is reset when I had a new package dependency.

Would you agree to reopen this issue ? I could make a PR to add the `allowedHosts` option.  
Another possibility would be to have a way to add options to the WebpackDevServer from app-config.yaml.

Additionally, the doc for [running behind a corporate proxy](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md) could be improve to advise about the `app.listen.host` option when `app.baseUrl` is not `localhost:`.

What do you guys think ?

**Comment by nnganesha** [comment]
Yes, I do agree. adding the option will be really helpful.

**Comment by patricekrakow** [comment]
I am still getting "Invalid Host header" when I install Backstage on <https://killercoda.com/playgrounds/scenario/ubuntu>, when I keep the default `baseURL` in the `app`:

```yaml
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  listen:
    host: 0.0.0.0
    port: 3000
```

As explained above, I thought I just have to update the `baseUrl` with the URL used in front of the Killercoda proxy (called _Traffic Port Accessor_). It seems logic as the Host header will then be inline with the host within the `baseUrl`. However when I do:

```yaml
app:
  title: Scaffolded Backstage App
  baseUrl: https://8dcf49c5-bcdb-4bfc-b1af-061b07b5104f-10-244-4-138-3000.spch.r.killercoda.com/
  listen:
    host: 0.0.0.0
    port: 3000
```

I am getting the following error:

```text
Error: Missing required config value at 'app.https.certificate.cert'
```

when starting the App using `yarn dev` or `yarn start`.

**Comment by elidhu** [comment]
I tried this @patricekrakow and it did, in fact, work

**Comment by guilherme-ptml** [comment]
that also worked for me using [traefik](https://traefik.io/traefik/)
