### ISSUE TITLE
RFC: Backend Service Discovery

### ISSUE THREAD

**Issue by freben** [spotify/backstage#1847]
# Background

Backend plugins (including the proxy and graphql plugins) that supply different pieces of functionality in the Backstage ecosystem need to communicate amongst each other. When they are deployed separately, they need to be able to locate the API endpoints of other plugins and services, in order to make requests to them.

Examples:

- The payload of a scaffolder request may contain the ID of a template, which the scaffolder wants to resolve in the catalog. It would then make an HTTP request to the catalog API for the data of that particular template.
- The graphql plugin may be deployed as part of the main backend, and its resolvers may then want to call out to a separately deployed catalog, lighthouse, etc.

# Proposed Interface

We propose to start out with a minimal, fairly explicit, code-based solution to start with. A plugin, when being initialized, is passed an instance of a service lookup interface that is able to find endpoints based on a plugin ID.

Example implementation:

```ts
/**
 * A basic service endpoint resolver.
 */
export type EndpointResolver = {
  /**
   * Returns the current set of endpoints where the given service can be reached.
   *
   * @param serviceName The opaque "name" to look up, for example a plugin ID
   * @returns A list of URLs to endpoint roots
   */
  resolve(serviceName: string): Promise<URL[]>;
}
```

A service name is an opaque identifier of the service whose endpoints we want to reach. We suggest that initially these are just plain backend plugin IDs, e.g. `"catalog"`.

The returned list consists of zero or more URLs. The caller may choose freely among them with any strategy. The endpoint resolver MAY choose to randomize the order of returned items on each call to support naive load balancing.

The `resolve` call is expected to be reasonably fast. The caller shall be able to call it for each outgoing request without worry for negative performance impact from the resolver itself.

# Initial Implementation

The first implementation of this interface may simply be driven by the app-config and/or have some hard coded behaviors. This can be extended later to more advanced resolvers. The company adopting Backstage will also be free to inject specific implementations of this interface that match their unique service lookup needs.

# Future Extension

Some ideas for future additions:

* Add SRV record lookup support
* Add support for bridging to third party service discovery services
* Add health checks and return known healthy endpoints
* Implement some load balancing scheme

# Limitations

This solution does not initially take health checking, fallbacks and load balancing into account. Those are hard to perform properly without being in the actual request path. When several endpoints are returned, it is up to clients to deal with that as they see fit.

**Comment by benjdlambert** [comment]
My concern with adding the path into the returned value is something thats not really supported many service discovery methods, it's normally just a hostname. Do we think this might become a problem when trying to integrate with things like k8s or consul?

**Comment by benjdlambert** [comment]
It feels to me like the dns part should take care of resolving where the proxy lives, and if we want to put these services behind the proxy that's a different concern? If that makes sense?

**Comment by benjdlambert** [comment]
Maybe all this is a non-issue, but just bringing it up as i've not really seen service discovery done with the path appended and taking into account the proxy aspect

**Comment by freben** [comment]
@benjdlambert updated to return `URL[]` instead of `string[]`

**Comment by Rugvip** [comment]
Regarding the path concern we likely wouldn't plug existing service discovery mechanisms straight into this API. Just thinking something like

```ts
const resolve = (pluginId: string) => {
  const services = await consul.catalog.service.nodes(pluginId)
  return services.map(s => `http://${s.Address}:${s.ServicePort}/${pluginId}`)
}
```

A separate thing that could be good to work into the low-level contract for service discovery would be observability. I'm in no way sold on that idea though, as there are many other ways to solve that and adds a bit of complexity. It may be that it's really nice to have for some use-cases, and it's a bit of a one-way thing where it's easy to implement single lookups on an observable stream, but tedious to turn single lookups into a stream of updates.

Taking the discussions from earlier today into account, but backtracking a little bit, and adding observability, I'm thinking something like this for the interface:

```ts
type HttpEndpoint = {
  url: string
}

type EndpointResolver = {
  resolvePlugin(pluginId: string): Observable<HttpEndpoint[]>;
}
```

Idea here is that we start off with only doing communication between plugins, as that keeps the scope of what we need to support much more narrow, both for now and in the future. We also assume that all traffic is HTTP, and with that we stick to simple URLs as the discovery output. We still wrap it in an object for forwards compatibility though.

**Comment by Rugvip** [comment]
Another option is to step this down a level and only consider consider making consumptions inside plugins very simple, and not really leaving any work left to do for plugins themselves. Basically just returning the `baseUrl` for the plugin you're requesting. Something like this:

```ts
type PluginResolver = {
  resolve(pluginId: string): Promise<string>;
}
```

Where the returned string is the base HTTP URL to use for communicating with the plugin. It is then up to the 
resolver implementation to do any kind of load balancing if the service discovery mechanism provides multiple targets to choose from.

It's a very simple option that gets us going, and if a need pops up it could be possible to extend the interface to also provide more advanced discovery. Although tbh I think it's more likely that we'd be reaching for gRPC rather than trying to do fancy service discovery with plain HTTP.

I also looked a bit at using the pattern for gRPC client load balancing in Go, which is to register custom protocol handlers that resolves to a watchable set of addresses. With that it could be possible to do something like `plugin://<pluginId>/`, but node doesn't really seem to have support for anything like that.

On that topic I'm also seeing that if we want to do any kind of advanced client-side discovery or lookaside load balancing, it seems to me that we'd really need to provide clients for the communication as well. Basically I'm worried about putting too much of the burden on plugin authors, and would prefer to instead keep things simple but maybe a bit dumb. Ofc gRPC could solve a bunch of these problems but it's too much to enforce that too :grin:
