### ISSUE TITLE
Tabs inside a Page component is broken

### ISSUE THREAD

**Issue by paul-frybarger** [spotify/backstage#2048]
Using the `Tabs` component inside of a `Page` causes the browser to hang.

## Expected Behavior

Tabs appear as shown in the storybook (https://backstage.io/storybook/?path=/story/tabs--default)

## Current Behavior

The browser hangs and throws an out of memory error.

<img width="1675" alt="Screenshot 2020-08-20 at 10 17 03" src="https://user-images.githubusercontent.com/57765564/90786352-5fca8d00-e2fb-11ea-9d4e-c31453eb2ba3.png">

<img width="1673" alt="Screenshot 2020-08-20 at 10 17 28" src="https://user-images.githubusercontent.com/57765564/90786356-60fbba00-e2fb-11ea-97e1-236a35ad5c19.png">

## Possible Solution

The problem occurs in this `useEffect` block: https://github.com/spotify/backstage/blob/bbd75a0981a5b7418ecf1afa2124738d7b18f494/packages/core/src/components/Tabs/Tabs.tsx#L91-L108

By debugging I can see that during the first render the `wrapperWidth` is -30. This causes `newChunkedElementSize` to be -1 and ultimately the `chunkArray` method runs forever.

It may have something to do with the grid layout, which causes the width of the wrapper to be 0 during the initial render. I'm not too familiar with this, otherwise I would try to fix the problem.

## Steps to Reproduce

```
export default function ServicePage() {
  return (
    <Page theme={pageTheme.service}>
      <Header
        title="my-service"
        type="service">
        <HeaderLabel label="Owner" value="me"/>
      </Header>
      <Tabs
        tabs={[...Array(4)].map((_, index) => ({
          label: `ANOTHER TAB`,
          content: <div>Content {index}</div>,
        }))}
      />
    </Page>
  );
}
```

**Comment by freben** [comment]
Hi! So I've been looking at this a bit. Firstly yeah, `chunkArray` definitely is buggy and I am making a pull request to address that.

But even fixing that, there's another issue. In your example code, the wrapping div around the tabs has nothing to keep it wide enough, so it collapses and gets narrowed into nothing if you touch the width of the window. That triggers a second bug. That's of course unexpected, and I will look into that too, BUT ...

Thirdly, the actual fix for you, is to use the `HeaderTabs` component instead of `Tabs` :) It is made for this exact purpose, and is connected in the CSS to the proper slot of the grid model that it happens to be part of. Therefore its placement and size automatically becomes correct. It is explicitly made for second-level navigation within a page.

So would you mind trying out your solution with the `HeaderTabs` component and report back whether that works better? Its props interface is a bit different but I am sure you'll be able to make it work pretty easily.

**Comment by paul-frybarger** [comment]
Yeah, makes sense. I think with your fixes this can be closed now. Thanks again!
