### ISSUE TITLE
Unable to ingest from Azure git repos

### ISSUE THREAD

**Issue by mfrinnstrom** [spotify/backstage#2254]
I tried ingesting a template from a private Azure git repo but got an error. After some investigation it seems that the generated URL doesn't correspond with what is in the Azure docs.

## Expected Behavior
As per [this](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-6.0) documentation the URL should be in the following format:

`GET https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/items?path={path}&api-version=6.0`

## Current Behavior
The currently generated URL looks like the following:

`GET https://dev.azure.com/{organization}/{project}/_apis/sourceProviders/TfsGit/filecontents?repository={repositoryId}&commitOrBranch=undefined&path={path}&api-version=6.0-preview.1`

I have not tried with a Team Foundation Version Control (TFVC) repo so I'm not sure if that works and what would happen if the URL is changed.

## Possible Solution
Change AzureApiReaderProcessor.ts to the documented URL.

## Steps to Reproduce

1. Go to register an existing component
2. Supply a URL for a private Azure repo

## Your Environment

- NodeJS Version (v12): v12.18.3
- Operating System and Version (e.g. Ubuntu 14.04): VS Code Node.js devcontainer
- Browser Information: Chrome 85.0.4183.83

**Comment by freben** [comment]
Hi, and thanks for reporting.

I am not familiar with the Azure APIs and offerings myself, but [commented on the original PR](https://github.com/spotify/backstage/pull/2081#discussion_r476437869) for this that it looked like it implemented one of several providers. And indeed, the [tfvc API docs](https://docs.microsoft.com/en-us/rest/api/azure/devops/tfvc/items/get?view=azure-devops-rest-6.0) do list a different URL for items.get.

There are at least two possible paths forward:

- Give them a distinct location type each. It currently is `azure/api`, but could be split into e.g. `azure/tf` and `azure/git` or similar.
- Make the existing processor support both formats automatically.

The latter would be the most convenient from a user standpoint.

Since I do not have an Azure environment to play with, could you @mfrinnstrom and/or @o-farooq check if the input URLs as seen in the browser location bar are the same no matter what the repo type is? The plugin currently shows

`https://dev.azure.com/{organization}/{project}/_git/reponame?path={path}&version=GB{commitOrBranch}&_a=contents`

as the expected format to convert from. Is for example the `_git` part different for you, @mfrinnstrom?

If they are different, it would be easy to select in code what target format to convert to. If they are the same, you may have to add an additional API call to know what underlying API to use.

Would you like to contribute a fix to support both providers?

**Comment by mfrinnstrom** [comment]
Hello,

The link for a file when browsing a git repo in the browser is the following:

`https://dev.azure.com/{organization}/{project}/_git/{reponame}?path={path}`

So it seems to be the same which will make it a bit more work I guess.

**Comment by freben** [comment]
OK, thanks for checking.

It would be interesting to see if one of them happens to have a fallback to the other :) Like if @o-farooq used the _git version of the API and it still worked for the TFS repo. It does look like kind of a generic form.

**Comment by mfrinnstrom** [comment]
I just tried creating a TFS repo and got the following URL in the browser:

`https://dev.azure.com/{organization}/{project}/_versionControl?path=%24%2F{reponame}%2F{path}`

I get the URLs from the address bar in the browser so they might be different if you are copying from Visual Studio or something like that. I have never really used TFS either so I can't say if I'm doing something wrong when it comes to creating/using the repo.

**Comment by freben** [comment]
Oh OK, interesting - so that's indeed different to the format that @o-farooq made support for.

Would you be able to change the existing plugin (frontend and backend) to support these effectively THREE url formats, and then pick the API to use based on those URLs and possibly some extra API call? I would like to keep the momentum and getting it improved, but since we aren't azure users ourselves it would be great if the community contributed to make it better. Otherwise, we could wait and see if somebody else wants to attack it.

**Comment by freben** [comment]
I added two more labels to the issue in the mean time.

**Comment by mfrinnstrom** [comment]
I will try and make some time to update it tomorrow.

**Comment by o-farooq** [comment]
I was using the _git version for the git repo. did not try it with TFS.
used this API to get the file contents [Azure API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source%20providers/get%20file%20contents?view=azure-devops-rest-6.0). this supports external repositories supported by Azure Devops as well llike Github, Bitbucket etc which are defined in Azure devops. but my primary usecase was Git repo inside Azure devops. I tested source provider TfsGit to be working fine for private git repo in Azure devops . @mfrinnstrom what is the exact error you are getting back from Azure the error dialog will have the http status code and error . 
and can you try Source provide Git instead of TfsGit and does that make any difference

**Comment by o-farooq** [comment]
@mfrinnstrom the input url from browser is same in your case except the branch name . interesting when first time you access the default master branch there is no branch name i-e no version in url 

`https://dev.azure.com/{organization}/{project}/_git/{reponame}?path={path}` . 

change the branch and come back to master again it will have version `https://dev.azure.com/{organization}/{project}/_git/reponame?path={path}&version=GBmaster` 

this might be an issue as well , i will try without branch name and if that seems to be an issue will create a PR to not pass the version to API if it is not in the browser URL

**Comment by mfrinnstrom** [comment]
Hey @o-farooq.

Thanks for looking into this again. I now see that I get a 401 response with the current URL. If I update the code to the one that I suggested it works though.
I'm new to Azure Devops to I might have missed something in my PAT. I have only selected Code (Read) for now.

**Comment by freben** [comment]
Thanks both of you. Let me know if I can be of assistance, but it would be great if we could make all of those possible URLs work "out of the box" so users can just paste whatever they have in their browser while looking at the file contents.

A perhaps useful analogy is when looking at a file on github, then both the regular browse view 

`https://github.com/spotify/backstage/blob/master/catalog-info.yaml`

as well as the raw view

`https://raw.githubusercontent.com/spotify/backstage/master/catalog-info.yaml`

could be argued that they should be valid, different representations of the same file, that should "just work" (although I think at the moment, only the first works :)).

**Comment by mfrinnstrom** [comment]
@o-farooq I see now that you use the Build API for getting the files. I don't have a build pipeline configured for my repo so that might be the reason that I can't download the files the current way.

**Comment by o-farooq** [comment]
awesome @mfrinnstrom . yes the API you suggested looks more Azure devops git native if it works then it is better than the source provider one i used which is more geared towards external repos. it is not build api though , it is just more generic version that support all providers in Azure . regarding 401 i faced the similar issue you need to give following two permissions to PAT Code (Read); Tokens (Read & manage)

**Comment by o-farooq** [comment]
just tested, with source provider API the branch is a required parameter . whereas the API you suggested it is optional.
to support the default branch browser url which does not have branch in it the API you suggested is the way to go.
are you good to do the PR or I am happy to do it ?

**Comment by mfrinnstrom** [comment]
I tried adding the Tokens (Read & Manage) now then I got the following error.

`InputError: Failed to read location azure/api https://dev.azure.com/{organization}/{project}/_git/{repo}?path=%2Ftemplate.yaml, Error: https://dev.azure.com/{organization}/{project}/_git/{repo}?path=%2Ftemplate.yaml could not be read as https://dev.azure.com/{organization}/{project}/_apis/sourceProviders/TfsGit/filecontents?repository={repo}&commitOrBranch=undefined&path=/template.yaml&api-version=6.0-preview.1, 500 Internal Server Error at HigherOrderOperations.addLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:89:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async eval (webpack-internal:///../../plugins/catalog-backend/src/service/router.ts:98:22)`

I'm not sure how I feel about having to add that permission though.

**Comment by o-farooq** [comment]
the issue here is that the commitorbranch is undefined `https://dev.azure.com/{organization}/{project}/_apis/sourceProviders/TfsGit/filecontents?repository={repo}&commitOrBranch=undefined&path=/template.yaml&api-version=6.0-preview.1`

just append `&version=GBmaster` to your input url and it would work . this would prove the issue is missing branch and then we have to use the API you suggested

**Comment by mfrinnstrom** [comment]
Yes, I just tested and with the branch and the permission it works.

**Comment by o-farooq** [comment]
thanks @mfrinnstrom for raising this, i have created the PR in which it should work without specifying the branch name, used the API you suggested

**Comment by freben** [comment]
That's great - we do expect to be on a main/default branch since these types of files are expected to be continuously "integrated".

**Comment by mfrinnstrom** [comment]
@o-farooq I just tested your branch and it works great! I could also reduce the permissions for the PAT to only Code (Read) again. Thank you for fixing this!
