### ISSUE TITLE
[RFC] Kubernetes plugin foundations

### ISSUE THREAD

**Issue by mclarke47** [spotify/backstage#2461]
# Need:

Some background can be found in https://github.com/spotify/backstage/issues/632.

Kubernetes is quickly becoming a de facto standard for deployment and users would like to see details of their
services on Kubernetes in backstage.

# Problem

While Kubernetes gives a consistent API and user experience to developers, 
Kubernetes developer experience (DX) depends on the organisation that sets it up.

Organisations choose:

* Where Kubernetes is running
    * GKE
    * EKS
    * AKE
    * Non-managed
* How many clusters to run
    * Single multi-tenant cluster
    * Multiple for different teams
    * Multiple in different regions
    * Multiple in different cloud providers
* How users authenticate with Kubernetes
    * Username/password
    * Certificates
    * OAuth2
    * Service account tokens
* Authorization strategies (Kubernetes RBAC)
    * Open (read/write in anything)
    * Read anything, write only what is owned by the user
    * Read/write only what is owned by the user
    * Read anything, no write
    * Read only what is owned by the user, no write

Authentication tokens/sessions storage further complicates this.

For example:

* OAuth2 tokens need to be stored per user in a cookie
* Shared service account tokens should be stored in a backend plugin and not leaked to the user

This vastly complicates building a Backstage Kubernetes plugin that everyone can use easily.
We will need to potentially configure the plugin differently for each organisation running a Backstage App.

# Proposal

The main problems we will need to solve for a Backstage Kubernetes plugin are:

* How do we discover which Kubernetes cluster a service is running on?
* How does the user authenticate with that cluster?
    * How to use the correct authentication to enforce the correct authorization?

After we answer these questions we can easily request the Kubernetes objects and show them in the UI.

This RFC proposes to add the foundations for a Backstage Kubernetes plugin that will
solve these problems from the design specified in https://github.com/spotify/backstage/issues/632#issuecomment-658172675.

![Kubernetes backstage plugin](https://user-images.githubusercontent.com/6514980/87429872-53586380-c5dc-11ea-8518-5a3b9208e45b.png)

This design should solve these problems by allowing users to configure the K8S plugin to have k8s-service-locater and k8s-auth-translators that work with their Kubernetes setup.

The implementors will provide:

- [x] A (read only) Kubernetes UI plugin that integrates into the service catalog, with basic components for:
    - [x] Pod
    - [x] Replica Set
    - [x] Deployment
    - [x] ConfigMap
    - [ ] Secret
    - [x] Service
    - [x] Ingress
    - [x] HPA
- [x] A Kubernetes backend plugin to manage Auth and proxy to clusters
- [x] The interface for the cluster service locator (with implementations below)
    - [x] clusters from a config file
    - [ ] HTTP GET (service name to cluster details)
- [x] K8S auth translator (with implementations below)
    - [x] Google Auth to GKE auth (this is a risk, I'm not sure if it will work)
    - [x] Service account tokens per cluster (if Google Auth to GKE doesn't work)
- [x] Logic for fetching K8S components by configurable label `backstage.io/service: "some-service"` 
    
In the future this could be extended as follows:

* Supporting CRDs or other K8S Kinds
* Supporting different authentication methods
* Fetching the cluster location by different means

# Pros

* Will act as a foundation for Kubernetes contributions
* Will lay the foundation for integration with any K8S setup by creating interfaces for cluster location and authentication

# Cons

* Some users might have to contribute implementations for the auth/cluster location to get their setup working

**Comment by Rugvip** [comment]
@mclarke47 Think we can have this as the boundary towards presentation? :>

```ts
type KubernetesResourceApi = {
  getResourcesForEntity(entity: Entity): Promise<KubernetesResource[]>
}
```

That'd be a client-side API for which we provide some implementation, which in turn would needs things like `KubernetesClusterDiscoverer`, `KubernetesApiClientFactory` or whatever other fun things would pop up as a requirement to keep things generic ^_>. Auth would likely be pluggable in the backend though, given the nature of it.

Apart from this ^ early-engineering, I'd be interested in the unknowns that we need to figure out before we can be confident in the architecture. It sounds like resource kinds, and cluster and resource discovery are somewhat bounded problems where we just need to figure out a sane design, but auth is much more of an open problem. Do you think it make sense to make a focused spike towards figuring out what options we have for auth before starting the more broad effort of implementing the entire thing e2e? It may have some pretty broad implications for where we'll be able to make things pluggable.

**Comment by mclarke47** [comment]
I'm not sure it's necessary. I can see the auth decisions users make boiling down to either storing tokens in a cookie (OAuth tokens) or configuring backstage to add a token (service account tokens) on the plugin backend. 

I think it would make sense to support both types eventually. 

How users get those tokens is an bit of an open question because it's such a large area and it depends on the organisation.

I think the easiest one is probably service account tokens but I'm hoping that we can re-use the user's auth backstage already supports for K8S if it makes sense for the user.

**Comment by timurista** [comment]
At face value, it would seem this plugin is very similar to https://github.com/lensapp/lens which offers multi-cluster visualization and management (lens ide). They scrape the user's kubeconfig to regsiter existing clusters and you install a version of their helm chart to see metrics for the cluster. One of the drawback is that it is only for an individual, so it'd be great to leverage the users existing team / LDAP group so when a user logs in they can see all the clusters they have access to in their org. At the very least, maybe an integration with lens could be possible since its an electron app or using them as a starting point.

**Comment by mclarke47** [comment]
@timurista I think that's a really interesting suggestion! I have to agree about the drawback, I think we would want to offer more auth configurations than uploading an kubeconfig file.

I think from a UI perspective the real difference is lens is more focused at showing the state of Kubernetes from the operators perspective, while with a service catalog integration it would be more focused on the specific services the user is responsible for (i.e. not necessarily a holistic view of the cluster).

However this does make me think maybe later there should be a separate operator view that could re-use the kubernetes backend above and provide a similar view to lens (even like you say potentially re-using UI elements). 👍

**Comment by timurista** [comment]
Glad it was helpful suggestion @mclarke47 !
I'm intrigued by the `k8s auth translator.`

That would be a great service in and of itself to translate between Active Directroy, IAM and GKE roles, permissions for k8s.
But the authorization mechanism might vary a lot by company. 

Some companies might use active directory LDAP as the source of truth and then iam and gke roles would basically mirror the LDAP groups which happens during onboarding (admin ldap group ==> DevAdmin for account 1234 for example). But other companies might have a different setup. Perhaps they 1) have no central source of authority but instead separate roles across clouds / k8s clusters and service accounts, 2) have a different setup like their own DB they use for source of truth for authority, 3) delegate that to a third party solution like vault, onelogin or something else and an integration/plugin would need to be written.

The translator could grow very large quickly and the user would need to configure their authorization profile. To be useful outside gke, iam, it'd need to be flexible.

**Comment by timja** [comment]
FYI this is what's used on AKS for non interactive log in:
https://github.com/Azure/kubelogin

It's a credential exec plugin that handles the Azure specific bit, you can use service principal or user account with Azure RBAC for access built in.

I assume you'd write a plugin that handles these details but hopefully the information is helpful.

**Comment by mclarke47** [comment]
Thanks! I think that is definitely going to be useful for those who use Azure RBAC!

**Comment by RochesterinNYC** [comment]
Posting this here instead of as a comment on https://github.com/spotify/backstage/pull/2691 for a bit more visibility/potential feedback:

In starting implementation for using google auth for authenticating to K8s for the Kubernetes plugin, a lot of good feedback was given regarding what potential contracts there could be between the backend and frontend in this domain and what interfaces might we expose to allow anyone to plug in their own auth systems/processes.

### Thoughts/proposals regarding a potential contract/interfaces:

We could have an interface on the frontend called something like `KubernetesAuthProvider` for which an instance/implementation of this interface needs to implement `decorateRequestBodyForAuth` which is basically a definition of:
- how to fetch whatever information the backend needs to correctly decorate the `clusterDetails` for a cluster with the correct authentication token
- how to decorate the body of the request for K8s resource info with this fetched information

We could have an interface on the backend called something like `KubernetesAuthTranslator` for which an instance/implementation of this interface needs to implement `decorateClusterDetailsWithAuth` which is basically a definition of:
- How/what information to pull from the body of the request for K8s resource info
- What to do with this information and how to properly fill the `serviceAccountToken` field of each `clusterDetails` with a valid authentication token.

Highly open to better names for any of this stuff.

### Walkthrough

Roughly what would happen when you click on the Kubernetes plugin for your catalog component/application:

- Frontend: Gets information about which `KubernetesAuthProvider` to use via making a request to the backend
- Backend: Gets request for which `KubernetesAuthProvider` to use from backend and checks `kubernetes.clusters` part of config for this info (namely which values are specified in the `authProvider` key/field for clusters) and responds to frontend with this information
- Frontend: Creates instances of the `KubernetesAuthProvider` for each authProvider the backend returned and invokes some `KubernetesAuthProvider` interface method (ex. `decorateRequestBodyForAuth`) that does whatever is needed (could be no-op in case of `serviceAccount` provider as the `serviceAccountToken` is already specified in the config in this case or it could be some oauth dance like with Google auth) to get the information required for the backend, send this to backend along with K8s resource requests
- Backend: Receives request for K8s resource info for a component 
  - Configured cluster locator returns all cluster details
  - For each clusterDetail/cluster, a specific object implementing the `KubernetesAuthTranslator` interface (which object/class is created is dictated by the `authProvider` specified for the cluster in the config) is created that gets passed the whole request body
  - Invokes some `KubernetesAuthTranslator` interface method (ex. `decorateClusterDetailsWithAuth`) that uses the info in the passed request body to decorate the clusterDetail appropriately (specifically the `serviceAccountToken` field)

### More specific walkthroughs/examples

Here are two specific examples/walkthroughs of this contract/these interfaces (I bolded the parts of each example that differ from each other):

Example of this specifically for a setup with some clusters using Google auth and some with the `serviceAccount` authProvider:

- Frontend gets information about which auth providers to use from backend via request
- Backend checks `kubernetes.clusters` part of config and sees **`google` and `serviceAccount` as the two different `authProvider`s specified across various clusters, returns response to frontend with `google`, `serviceAccount`**
- Frontend creates an instance of:
  - **`serviceAccountKubernetesAuthProvider`: a class implementing the `KubernetesAuthProvider` interface, has no-op logic for its `decorateRequestBodyForAuth` method implementation)**
  - **`googleKubernetesAuthProvider`:  a class implementing the `KubernetesAuthProvider` interface, has logic for its `decorateRequestBodyForAuth` method implementation that uses googleAuth to get a google auth token and puts this token into the request body)** 
- Frontend invokes `decorateRequestBodyForAuth` on both of these instances to prepare a request body and then sends the actual request (including the prepared body) to backend requesting info on K8s resource requests (so the request body just contains **the google token**).
- Backend gets K8s resource info request
- Backend fetches all cluster details (current behavior)
- Backend, for each cluster, checks the configured `authProvider`, creates an instance of the corresponding class that implements the `KubernetesAuthTranslator` interface, and invokes `decorateClusterDetailsWithAuth` for that instance.
  - **For clusters configured with `authProvider` of 'serviceAccount', the `serviceAccountKubernetesAuthTranslator` is used and its `decorateClusterDetailsWithAuth` would do a no-op as clusterDetails with this authProvider already contain a `serviceAccountToken` value.**
  - **For clusters configured with `authProvider` of 'google', the `googleKubernetesAuthTranslator` is used and its `decorateClusterDetailsWithAuth` would have logic to pull the google token from the request body and set that as the serviceAccountToken.**
- Backend then has auth for each clusterDetails set and goes ahead and passes all this info to the KubernetesFetcher which does its job of making the K8s API requests and getting the resource info.

Example of this specifically for a setup with all clusters using company A's custom auth:

- Frontend gets information about which auth providers to use from backend via request
- Backend checks `kubernetes.clusters` part of config and **sees `companyAK8sAuth` as the only `authProvider` specified across clusters, returns response to frontend with `companyAK8sAuth`**
- Frontend creates an instance of:
  - **`companyAK8sAuthProvider`: a class implementing the `KubernetesAuthProvider` interface, for its `decorateRequestBodyForAuth` method implementation it takes the current user's LDAP name and puts that into the request body)**
- Frontend invokes `decorateRequestBodyForAuth` on this instance to prepare a request body and then sends the actual request (including the prepared body) to backend requesting info on K8s resource requests (so the request body just contains **the LDAP name**).
- Backend gets K8s resource info request
- Backend fetches all cluster details (current behavior)
- Backend, for each cluster, checks the configured `authProvider`, creates an instance of the corresponding class that implements the `KubernetesAuthTranslator` interface, and invokes `decorateClusterDetailsWithAuth` for that instance.
 -  **For clusters configured with `authProvider` of 'companyAK8sAuth', the `companyAK8sAuthKubernetesAuthTranslator` is used and its `decorateClusterDetailsWithAuth` would: **
    -  **pull the LDAP username from the request body **
    -  **query a microservice in company A's infra/network that checks that the LDAP user has proper access to each cluster and if so, returns an auth token **
    -  **sets the `serviceAccountToken` for that cluster to the returned token**
- Backend then has auth for each clusterDetails set and goes ahead and passes all this info to the KubernetesFetcher which does its job of making the K8s API requests and getting the resource info.

Thoughts/feedback?

**Comment by mclarke47** [comment]
The work here is now done 🎊 . Suggestions for further improvements are in https://github.com/spotify/backstage/issues/2857
