### ISSUE TITLE
[Scaffolder] Stage failed with error: Not Found 

### ISSUE THREAD

**Issue by emmaindal** [spotify/backstage#2478]
## Expected Behavior

Be able to create a component when all required information is filled in or get a more user friendly error message so that I can investigate in what did go wrong.

## Current Behavior

info: Will now store the template {"id":"278635e0-bf3c-4bcc-b28c-d96c7c55022a","stage":"Publish template","timestamp":"2020-09-15T18:01:12.301Z"}
error: Stage failed with error: Not Found {"id":"278635e0-bf3c-4bcc-b28c-d96c7c55022a","stage":"Publish template","timestamp":"2020-09-15T18:01:12.574Z"}

**Comment by tjperry07** [comment]
To add, I experienced this issue when trying to create a React Template and a Docs Template.

**Comment by dtuite** [comment]
Semi-unrelated but we are working on validating template values [here](https://github.com/RoadieHQ/backstage/pull/18). The. first part is in review in our fork but will be pull requested upstream to spotify/backstage soon.

**Comment by benjdlambert** [comment]
So I believe the error message of `not found` comes from github when trying to create a repo in an organisation that doesn't exist. We up until recently only supported organisations to create repositories in, but however, since https://github.com/spotify/backstage/pull/2433 this is no longer required. The issue comes now however, is that we haven't released this code yet for the `create-app` usage, so unfortunately, the code only lives on master until we do a release. 

We are planning a release ASAP, just catching up on some stuff what's happened the last few days whilst @spotify/backstage-core have been on an offsite.

Will keep this issue open and will let you know when it's fixed and you can update to the latest code!

/b

**Comment by benjdlambert** [comment]
Can we close this now? Think it should be fixed part of the release we made recently.

**Comment by benjdlambert** [comment]
@emmaindal @OrkoHunter @tjperry07?
