### ISSUE TITLE
Backend fails to start

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#2493]
Get the following error when starting the `packages/backend`:

```
Backend failed to start up Error: Missing required config value at 'scaffolder.github.token'
    at ConfigReader.getString (webpack-internal:///../config/src/reader.ts:231:13)
    at createPlugin (webpack-internal:///./src/plugins/scaffolder.ts:46:30)
    at main (webpack-internal:///./src/index.ts:93:104)
```

**Comment by freben** [comment]
You merged a fix for that a couple hours ago right? :) https://github.com/spotify/backstage/pull/2492

**Comment by freben** [comment]
Oh - does it require that the env variable really is set as well? Ok.

**Comment by stefanalund** [comment]
Is this only when running an App? My problem is when running the example app.

**Comment by freben** [comment]
Ping @timja and @benjdlambert 

This one should probably not be required. The backend should at least start up without it

**Comment by timja** [comment]
checking

**Comment by timja** [comment]
It starts for me fine with the API token present

@stefanalund  can you try this please?

```
export GITHUB_ACCESS_TOKEN=a
yarn start
```

```
export GITHUB_ACCESS_TOKEN=a
yarn start-backend
```

**Comment by stefanalund** [comment]
Running `yarn start-backend` did the trick. I had missed this new way to start the backend. Thanks!

**Comment by timja** [comment]
@stefanalund I would leave the ticket open, it shouldn't error without the env variable

**Comment by benjdlambert** [comment]
@timja could you take a look at this?

I guess it should be `getOptionalConfig` instead somewhere in the stuff we merged last few days?

**Comment by Rugvip** [comment]
The convention is to wrap the config reading in a `try - catch` and only re-throw if we're in `NODE_ENV === 'production'`.

Tbh I think we may wanna move that to the `backend` and `@backstage/backend-common` service builder or smth. Bit tedious to have to implement for every plugin. Having it as a default also reduces the blast radius of these small issues by a lot

**Comment by benjdlambert** [comment]
@timja - follow @Rugvip's suggestion then. 👍

**Comment by timja** [comment]
I've had a look, seems easier to fix after: https://github.com/spotify/backstage/pull/2426

Pattern is here:
https://github.com/spotify/backstage/blob/f1ca8daee826eae3fcd6dfefa8fd2f495710a9c1/plugins/auth-backend/src/service/router.ts#L74

Code that is causing the issue:
https://github.com/spotify/backstage/blob/f1ca8daee826eae3fcd6dfefa8fd2f495710a9c1/packages/backend/src/plugins/scaffolder.ts#L49

wrapping it in try catch isn't enough as then you don't have a publisher and need to adjust the code to handle null publisher which doesn't seem right.

imo better once there's a list of publishers.

if the other PR is going to be merged soon this can be fixed easily on top.
Otherwise the abstraction to add multiple providers could be extracted out?

**Comment by timja** [comment]
Lol now we have:

```
Backend failed to start up Error: Missing required config value at 'scaffolder.gitlab.api.token'
    at ConfigReader.getString (webpack-internal:///../config/src/reader.ts:231:13)
    at createPlugin (webpack-internal:///./src/plugins/scaffolder.ts:81:38)
    at main (webpack-internal:///./src/index.ts:93:104)
```

Fixing it...

**Comment by timja** [comment]
PR: https://github.com/spotify/backstage/pull/2500
