### ISSUE TITLE
Kubernetes plugin: Add cluster authentication

### ISSUE THREAD

**Issue by mclarke47** [spotify/backstage#2552]
- [x] Add ability to translate g cloud auth to K8S credentials
- [x] Add ability to configure service accounts to be used for a cluster in a configuration file
- [x] Add an interface so that more implementations can be added
- [x] Add any necessary tests

Part of https://github.com/spotify/backstage/issues/2461

**Comment by RochesterinNYC** [comment]
Continuing discussions/brainstorming on the auth piece in this public issue here.

Although there are a lot of Kubernetes and related docs/blog posts and etc. on auth-ing to the Kubernetes API via Certificates, Certificate Requests, and the like, it seems that the Kubernetes API on a GKE cluster is able to accept Google auth tokens as the auth token used in the `Bearer` header.

Here's an illustration of this:

I'm currently authenticated via `gcloud` as my Spotify company account.

```
$ gcloud auth list
                          Credentialed Accounts
ACTIVE  ACCOUNT
*       jameswen@spotify.com

To set the active account, run:
    $ gcloud config set account `ACCOUNT`
```

I print a Google access token (I'm making the possibly incorrect assumption here that this is what the existing or planned GCP auth integration for Backstage will essentially have or make available once a Backstage user authenticates/signs into Backstage via Google auth):

```
$ gcloud auth print-access-token
ya29.[...]qlQ
```

I get the master IP for one of our GKE clusters:

```
$ gcloud container clusters describe production-europe-west1 --region europe-west1 --project <GCP project> | grep "endpoint:"
endpoint: <x.x.x.x>
```

I make a curl request to the GKE cluster master/K8s API to see Deployment resources for one of our Namespaces (note that the Google access token from before is used in the `Authorization: Bearer [...]` header:

```
$ curl -X GET https://x.x.x.x/apis/apps/v1/namespaces/warpspeed/deployments --header "Authorization: Bearer ya29.[...]qlQ" --insecure -I

HTTP/2 200
audit-id: 87b931ec-f123-4ed5-ae9d-c0284b2cfeae
content-type: application/json
date: Thu, 24 Sep 2020 03:58:16 GMT

$ curl -X GET https://x.x.x.x/apis/apps/v1/namespaces/warpspeed/deployments --header "Authorization: Bearer ya29.[...]qlQ" --insecure
{
  "kind": "DeploymentList",
  "apiVersion": "apps/v1",
  "metadata": {
    "selfLink": "/apis/apps/v1/namespaces/warpspeed/deployments",
    "resourceVersion": "2239659998"
  },
  "items": [
    {
[...]
    }
  ]
```

Showing here that it returns a 401 if I use an improper token:

```
$ curl -X GET https://x.x.x.x/apis/apps/v1/namespaces/warpspeed/deployments --header "Authorization: Bearer ya29.[...]j" --insecure 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
```

**Comment by RochesterinNYC** [comment]
With that in mind, it seems like we can simply use the Google auth token that Backstage authentication with GCP/Google will return. A specific token is only valid for about 30 minutes, but I'm guessing that the Google authentication piece of Backstage will have or already has logic for refreshing the token based off of the refresh token that gets returned by Google on initial auth/this isn't really a Kubernetes/GKE auth concern.

**Comment by mclarke47** [comment]
That's great news! Sounds like we'll just need to get the ui plugin to send it to the backend plugin and add a way to configure the backend to expect the auth to come from the ui

**Comment by Rugvip** [comment]
@RochesterinNYC Yep, tokens are very much refreshed, just gotta be sure to ask for a new one for every request and not store it in a class field e.g.

Sounds like a good starting point though! It kinda forces out the most granular design where there's separate auth for every request

**Comment by RochesterinNYC** [comment]
Posting this here instead of as a comment on https://github.com/spotify/backstage/pull/2691 for a bit more visibility/potential feedback:

In starting implementation for using google auth for authenticating to K8s for the Kubernetes plugin, a lot of good feedback was given regarding what potential contracts there could be between the backend and frontend in this domain and what interfaces might we expose to allow anyone to plug in their own auth systems/processes.

### Thoughts/proposals regarding a potential contract/interfaces:

We could have an interface on the frontend called something like `KubernetesAuthProvider` for which an instance/implementation of this interface needs to implement `decorateRequestBodyForAuth` which is basically a definition of:
- how to fetch whatever information the backend needs to correctly decorate the `clusterDetails` for a cluster with the correct authentication token
- how to decorate the body of the request for K8s resource info with this fetched information

We could have an interface on the backend called something like `KubernetesAuthTranslator` for which an instance/implementation of this interface needs to implement `decorateClusterDetailsWithAuth` which is basically a definition of:
- How/what information to pull from the body of the request for K8s resource info
- What to do with this information and how to properly fill the `serviceAccountToken` field of each `clusterDetails` with a valid authentication token.

Highly open to better names for any of this stuff.

### Walkthrough

Roughly what would happen when you click on the Kubernetes plugin for your catalog component/application:

- Frontend: Gets information about which `KubernetesAuthProvider` to use via making a request to the backend
- Backend: Gets request for which `KubernetesAuthProvider` to use from backend and checks `kubernetes.clusters` part of config for this info (namely which values are specified in the `authProvider` key/field for clusters) and responds to frontend with this information
- Frontend: Creates instances of the `KubernetesAuthProvider` for each authProvider the backend returned and invokes some `KubernetesAuthProvider` interface method (ex. `decorateRequestBodyForAuth`) that does whatever is needed (could be no-op in case of `serviceAccount` provider as the `serviceAccountToken` is already specified in the config in this case or it could be some oauth dance like with Google auth) to get the information required for the backend, send this to backend along with K8s resource requests
- Backend: Receives request for K8s resource info for a component 
  - Configured cluster locator returns all cluster details
  - For each clusterDetail/cluster, a specific object implementing the `KubernetesAuthTranslator` interface (which object/class is created is dictated by the `authProvider` specified for the cluster in the config) is created that gets passed the whole request body
  - Invokes some `KubernetesAuthTranslator` interface method (ex. `decorateClusterDetailsWithAuth`) that uses the info in the passed request body to decorate the clusterDetail appropriately (specifically the `serviceAccountToken` field)

### More specific walkthroughs/examples

Here are two specific examples/walkthroughs of this contract/these interfaces (I bolded the parts of each example that differ from each other):

Example of this specifically for a setup with some clusters using Google auth and some with the `serviceAccount` authProvider:

- Frontend gets information about which auth providers to use from backend via request
- Backend checks `kubernetes.clusters` part of config and sees **`google` and `serviceAccount` as the two different `authProvider`s specified across various clusters, returns response to frontend with `google`, `serviceAccount`**
- Frontend creates an instance of:
  - **`serviceAccountKubernetesAuthProvider`: a class implementing the `KubernetesAuthProvider` interface, has no-op logic for its `decorateRequestBodyForAuth` method implementation)**
  - **`googleKubernetesAuthProvider`:  a class implementing the `KubernetesAuthProvider` interface, has logic for its `decorateRequestBodyForAuth` method implementation that uses googleAuth to get a google auth token and puts this token into the request body)** 
- Frontend invokes `decorateRequestBodyForAuth` on both of these instances to prepare a request body and then sends the actual request (including the prepared body) to backend requesting info on K8s resource requests (so the request body just contains **the google token**).
- Backend gets K8s resource info request
- Backend fetches all cluster details (current behavior)
- Backend, for each cluster, checks the configured `authProvider`, creates an instance of the corresponding class that implements the `KubernetesAuthTranslator` interface, and invokes `decorateClusterDetailsWithAuth` for that instance.
  - **For clusters configured with `authProvider` of 'serviceAccount', the `serviceAccountKubernetesAuthTranslator` is used and its `decorateClusterDetailsWithAuth` would do a no-op as clusterDetails with this authProvider already contain a `serviceAccountToken` value.**
  - **For clusters configured with `authProvider` of 'google', the `googleKubernetesAuthTranslator` is used and its `decorateClusterDetailsWithAuth` would have logic to pull the google token from the request body and set that as the serviceAccountToken.**
- Backend then has auth for each clusterDetails set and goes ahead and passes all this info to the KubernetesFetcher which does its job of making the K8s API requests and getting the resource info.

Example of this specifically for a setup with all clusters using company A's custom auth:

- Frontend gets information about which auth providers to use from backend via request
- Backend checks `kubernetes.clusters` part of config and **sees `companyAK8sAuth` as the only `authProvider` specified across clusters, returns response to frontend with `companyAK8sAuth`**
- Frontend creates an instance of:
  - **`companyAK8sAuthProvider`: a class implementing the `KubernetesAuthProvider` interface, for its `decorateRequestBodyForAuth` method implementation it takes the current user's LDAP name and puts that into the request body)**
- Frontend invokes `decorateRequestBodyForAuth` on this instance to prepare a request body and then sends the actual request (including the prepared body) to backend requesting info on K8s resource requests (so the request body just contains **the LDAP name**).
- Backend gets K8s resource info request
- Backend fetches all cluster details (current behavior)
- Backend, for each cluster, checks the configured `authProvider`, creates an instance of the corresponding class that implements the `KubernetesAuthTranslator` interface, and invokes `decorateClusterDetailsWithAuth` for that instance.
 -  **For clusters configured with `authProvider` of 'companyAK8sAuth', the `companyAK8sAuthKubernetesAuthTranslator` is used and its `decorateClusterDetailsWithAuth` would: **
    -  **pull the LDAP username from the request body **
    -  **query a microservice in company A's infra/network that checks that the LDAP user has proper access to each cluster and if so, returns an auth token **
    -  **sets the `serviceAccountToken` for that cluster to the returned token**
- Backend then has auth for each clusterDetails set and goes ahead and passes all this info to the KubernetesFetcher which does its job of making the K8s API requests and getting the resource info.

Thoughts/feedback?

**Comment by freben** [comment]
First question that comes to mind is, does there have to be collaboration between frontend and backend? Are the auth methods different from cluster to cluster, or can the Backstage integrator just hard code one (or more?) decorator(s) on the client side and same on the server side - so the user always gets asked for oauth / always gets their username sent - whether it's needed at that particular point in time or not, but the backend is sure to always have what it needs?

This obviously only works if e.g. a single access token is viable to use for all auth needs where it's applicable for example. Sorry if it's a silly question, haven't read up on all of the gritty specifics to be honest :)

**Comment by mclarke47** [comment]
I think it looks good so far! I'm for the backend returning the auth providers required, as I think down the line it might make sense to have a way to configure your kubernetes clusters other than putting them in a config file. 

For example you might want to have them stored in zookeeper (or other config management system), or possibly another service could dynamically return the clusters, in order to support more ephemeral clusters. In that case it needs to be pretty dynamic.

**Comment by Rugvip** [comment]
Initial though is that I think we limit the frontend/backend contract to be only around decorating the request with additional headers, passing it through the body is less secure and also becomes a bit less flexible as you have to know the shape of the body and can't use body-less methods.

For the frontend interface something like this might make sense:

```ts
type KubernetesAuthApi = {
  getAuthHeaders(): Promise<{[name: string]: string}>
}
```

With that I'm also implying that auth would not be handled differently for different clusters in the frontend. If you have multiple different auth methods for different clusters in the backend, you just have to pass tokens for all of them with every request. It's basically what @freben is suggesting, just clarifying that we can support multiple clusters too. One addition could be to pass in the entity though, `getAuthHeaders(entity: Entity)`, that'd let the frontend do some basic selection if needed. With that you could actually implement the behaviour you're suggesting, by first doing a lookup via the backend, but imo not something we build now or ship as default.

What I'm really interested in then would be the contract on the backend and how clusters are described. Currently we have 

```ts
export interface ClusterDetails {
  name: string;
  url: string;
  authProvider: string | undefined;
  serviceAccountToken: string | undefined;
}
```

Wondering if we perhaps could have something that looks a bit more like this:

```ts
export interface ClusterDetails {
  name: string;
  url: string;
  userProvider: (reqHeaders: {[name: string]: string}) => Promise<User>; // k8s client user as passed to loadFromOptions
}
```

Along with the `KubernetesClusterLocator` interface that should provide a lot of flexibility in how clusters and their auth methods are provided. Could be via separate calls to other services, looking up the auth method and assigning `userProvider` as needed, or just a hardcoded list of clusters with service accounts, etc.

**Comment by freben** [comment]
Spinning along with @Rugvip's idea,

The config read by the frontend plugin could contain something like

```yaml
someParent:
  auth:
    googleAuthScopes: '...' # <- results in an x-backstage-k8s-google-access-token header being sent 
    username: true # <- results in an x-backstage-k8s-username header being sent
```

etc

**Comment by mclarke47** [comment]
I think we might be getting mixed up.

 > With that I'm also implying that auth would not be handled differently for different clusters in the frontend. If you have multiple different auth methods for different clusters in the backend, you just have to pass tokens for all of them with every request 

I think we're all on the same page with that.

The problem is the frontend doesn't (and can't) know what cluster the service is actually on and therefore doesn't know what auth types to send to the backend. Therefore the when you look at the kubernetes tab we need to: 

1. (frontend) pass the entity to the backend
2. (backend) figure out where the service is running
3. (backend) send back what auth providers are required to lookup the service
4. (frontend) do the authentication dances for each provider
5. (frontend) store the tokens for that service/user combination for subsequent lookups

**Comment by freben** [comment]
@mclarke47 the question is, is it possible to always send the union of all possible auth (as configured), bypassing the need for a query round-trip to ask for which one to send?

**Comment by Rugvip** [comment]
> The problem is the frontend doesn't (and can't) know what cluster the service is actually on and therefore doesn't know what auth types to send to the backend. Therefore the when you look at the kubernetes tab we need to:

This is what I meant we shouldn't care about in the frontend, and just send the union of all auth types.

**Comment by mclarke47** [comment]
I think it is for now, as we only have config driven cluster info. 

In the future though we might want to consider cluster info coming in from a another source:
* Hit the gcloud api looking for clusters that have a specific label (this would vastly simplify the configuration process)
* Same for AWS/Azure etc...
* A microservice or other in house tool

**Comment by freben** [comment]
Isn't there a (very) small set of possible auth types per org? I'm probably missing a detail somewhere.

**Comment by Rugvip** [comment]
Yeah that kinda thing could be useful in the future for a more turnkey solution, basically just give a list of a couple of providers and it's all spun up and working. Tbh you'll pretty much always have to configure auth individually for every provider though, unless you wanna hand over all the admin keys to backstage. Either way it should totally be possible to implement the discover cluster -> select provider auth flow via the backend with the interface I suggested, as long as we include the entity/serviceId in the method params. We can defer that for much later though

**Comment by Rugvip** [comment]
@freben not if you consider all the different providers the entire community could be using, and supporting them all with minimal config, but tbh I think we should keep that waaaaaay out of scope for now

**Comment by mclarke47** [comment]
@freben not if someone is using a multi cloud model for deploying their applications. 

They could in theory use AKS/GKE/EKS etc... or an combination of them.

**Comment by mclarke47** [comment]
It probably is out of scope for now, perhaps we should just ensure the frontend/backend config is on the same page. WDYT @RochesterinNYC

**Comment by freben** [comment]
Ok, understood, thanks for your patience :)

**Comment by RochesterinNYC** [comment]
Thinking about it more, I think having the frontend query the backend for all the authProviders it should be considering/potentially doing oauth for is something that could be done later. For the time being, simply fetching this information from the config (and maybe doing some more config validation on startup) should suffice.

**Comment by RochesterinNYC** [comment]
@Rugvip I'm not quite sure what this syntax/part of the interface means: `userProvider: (reqHeaders: {[name: string]: string}) => Promise<User>; // k8s client user as passed to loadFromOptions`

@Rugvip the point about it being a bit easier to fetch tokens from headers rather than the body makes sense. I didn't know that the headers are more secure than the body though, since my understanding was that both are encrypted when it comes to HTTPS.

But since there are potentially multiple auth providers in play and etc., we wouldn't be able to use a single header like the typical `Authorization: Bearer <token>` type thing, no? The `GoogleKubernetesAuthProvider` might stick the token into a header like `Google-Authorization: <google auth token>` while the `AWSKubernetesAuthProvider` might stick the token into a header like `AWS-Authorization: <AWS auth token>`. So implementations the KubernetesAuthProvider and KubernetesAuthTranslator would still need to basically implement logic for respectively "what header do I stick into the request" and "what header from the request do I consider".

With this, an instance of `KubernetesAuthProvider` would need to implement `decorateRequestBodyForAuth` which is basically a definition of:
- how to fetch whatever information the backend needs to correctly decorate the `clusterDetails` for a cluster with the correct authentication token
- how to decorate the headers of the request for K8s resource info with this fetched information

With this, an instance of `KubernetesAuthTranslator` would need to implement `decorateClusterDetailsWithAuth` which is basically a definition of:
- How/what information to pull from the headers of the request for K8s resource info
- What to do with this information and how to properly fill the `serviceAccountToken` field of each `clusterDetails` with a valid authentication token.

Unless, did you have an idea for how to munge multiple authentication tokens into a single header or etc.? In a way that the backend receiving the request and headers wouldn't need custom logic in place for each provider to pull its respective auth token from the request/headers?

**Comment by freben** [comment]
> @Rugvip I'm not quite sure what this syntax/part of the interface means: `userProvider: (reqHeaders: {[name: string]: string}) => Promise<User>; // k8s client user as passed to loadFromOptions`

It means that the single parameter reqHeaders is any string-key, string-value object, and the return value is a promise of a User object.

**Comment by Rugvip** [comment]
@RochesterinNYC What freben said, it could be called like this:

```
const user = await clusterInfo.userProvider({'Google-Token': 'xyz'})
```

Regarding token in body vs headers, the main reason is the convenience of not having to interact with the body for auth, and have a solution that works for any kind of requests without having to take the request body into account. WRT security it's idd encrypted just the same, but imo request bodies are more likely to be logged compared to all headers. You also need to parse the entire request to access the headers, meaning it's easier to execute DoS attacks with large payloads.

I was thinking multiple headers, but tbh I don't see how to avoid that even with a cluster discovery step, since we'd most likely wanna support that lookup resulting in multiple clusters with different auth strategies?

Playing with the idea that we'd pass auth strategy enums around, and put the tokens in the body, are you thinking something like this?

```
GET /api/kubernetes/clusters-for-entity?name=my-entity
->
{
  clusters: [{
    name: 'europe-1',
    auth: 'google',
  }, {
    name: 'europe-2',
    auth: 'azure',
  }],
}

POST /api/kubernetes/resources-for-entity
{
  name: "my-entity",
  clusterAuth: {
    "europe-1": { token: "my-google-token" },
    "europe-2": { token: "my-azure-token" },
  }
}
->
{
... bunch of resources
}
```

**Comment by RochesterinNYC** [comment]
Okay, not understanding how the `user` part of this potential method comes into play though? `userProvider: (reqHeaders: {[name: string]: string}) => Promise<User>; // k8s client user as passed to loadFromOptions`

Confused as it would be part of the `clusterDetails` and I'm not what the relation is between the user and cluster details/why a user needs to be returned by that method.

In this example of `const user = await clusterInfo.userProvider({'Google-Token': 'xyz'})`, the google token is all that the clusterDetails needs to be able to make the K8s API request?

**Comment by RochesterinNYC** [comment]
The bit about tradeoffs for headers vs. body makes sense to me.

Playing with the idea that we'd pass auth strategy enums around, and put the tokens in the body, I was thinking something a bit more like this:

```
Frontend --> Backend: GET /api/kubernetes/clusters-for-entity/my-entity
Backend --> Frontend:
{
  clusters: [{
    name: 'europe-1',
    auth: 'google',
  }, {
    name: 'europe-2',
    auth: 'azure',
  }], {
    name: 'europe-3',
    auth: 'azure',
  }], {
    name: 'europe-4',
    auth: 'azure',
  }],
}

Frontend: does google oauth and azure oauth once each to get tokens
Frontend --> Backend: 
POST /api/kubernetes/resources-for-entity/my-entity
{
  clusterAuth: {
    "google": { token: "my-google-token" },
    "azure": { token: "my-azure-token" },
  }
}
Backend: Based off of cluster config + what authProviders configured for each cluster, takes appropriate tokens from clusterAuth of body and decorates the serviceAccountToken field of each clusterDetails with them
Backend --> K8s API: Properly authenticated API/resource requests
Backend --> Frontend: 
{
... bunch of resources
}
```

**Comment by Rugvip** [comment]
@RochesterinNYC This user: https://github.com/spotify/backstage/blob/34c6f38bf97b0421eb42bdf80f6a07f1b4ca98db/plugins/kubernetes-backend/src/service/KubernetesClientProvider.ts#L74

The way I see it atm is that that user object is the end goal of the backend cluster authentication. If we can have something that is able to map whatever we get from the frontend and other sources to those user objects, we've pretty much solved authentication.

Regarding the in-body flow, it can in a way just be condensed down into this then (although I'm not saying we should implement it like this, just that this is the minimal model):

```
Frontend --> Backend: GET /api/kubernetes/auth-for-entity/my-entity
Backend --> Frontend:
{
  providers: ['google', 'azure']
}

POST /api/kubernetes/resources-for-entity/my-entity
{
  auth: {
    "google": { token: "my-google-token" },
    "azure": { token: "my-azure-token" },
  }
}
Backend --> Frontend: 
{
... bunch of resources
}
```

We should also be able to easily move the last request to user headers for the auth instead if we want to too, something like

```
Auth-google: { token: 'my-google-token' }
Auth-azure: { token: 'my-azure-token' }
```

Thinking about interfaces in the frontend we could end up with a `{ [provider: string]: () => Promise<JsonObject> }` map for providing tokens for the various providers. Something like this:

```ts
new KubernetesAuthApi({
  providers: {
    google: async () => ({ token: await googleAuthApi.getAccessToken('whatever-scope-is-needed') }),
    azure: async () => ({ token: await azureAuthApi.getAccessToken('whatever-scope-is-needed') }),
  },
})
```

Or just simply it all quite a bit by working only with tokens as opaque strings instead of json objects.

I'm still leaning towards an a higher-level interface that we could implement all this on top of, along with something much simpler.

**Comment by RochesterinNYC** [comment]
Don't we need an auth token more essentially than just the user ID or user identity ?

What you have regarding the in-body flow aligns with what I mentioned above regarding the KubernetesAuthProvider and KubernetesAuthTranslator interfaces and how they work (with the main difference being having the tokens in body vs. headers, which we can pretty easily change later). For the time being, I've implemented these interfaces and implementations of them for `serviceAccount` and `google` auth provider types via an additional commit on https://github.com/spotify/backstage/pull/2691, which works as of now in practice. I'd roughly suggest we go with that/try to get that merged and then iterate/change things around until we get to an interface that we're all happy with + is easy for Backstage developers/maintainers to use and extend?
