### ISSUE TITLE
Lighthouse plugin widgets/cards & entity integration

### ISSUE THREAD

**Issue by iain-b** [spotify/backstage#2605]
I'd like to add some features to the Lighthouse plugin and was hoping to get some input before I get too far into implementation. 

## Feature Suggestion

1. Add a Last Audit widget/card (not too sure what the preferred naming is for these) which could be displayed on the overview page for website components.
2. Add a Lighthouse tab to website components where detailed audit information is displayed

## Possible Implementation

Websites are identified in the lighthouse audit service by the url so I was thinking we could )optionally annotate website components with their url so that we can get audit information within the context of the catalog. 
E.g. `lighthouse.com/website-url: <website_url>`

For the widget, I'm thinking of perhaps two (so users can choose), the first of which something like this:
![image](https://user-images.githubusercontent.com/1415599/94256268-7929af00-ff21-11ea-8da8-3a007a188453.png)

And the second perhaps using `<GaugeProgress />` elements to display scores in each category? For reference, something like [this](https://backstage.io/storybook/?path=/story/progress-card--default) but multiple guages in one card I'm thinking.

The tab would simply display the same content as the lighthouse plugin page when you click through to a particular website. Ideally we could just render the component which renders the content below in the tab:
![image](https://user-images.githubusercontent.com/1415599/94257846-d4f53780-ff23-11ea-8dfe-45e2f257238e.png)

**Comment by stefanalund** [comment]
@javoire @fastfrwrd may have opinions about this.

**Comment by fastfrwrd** [comment]
@iain-b these both are wonderful ideas.

Storing the website url on the catalog is actually what we do internally with our legacy catalog system, so this is a very welcome feature. A note: you potentially want to consider making the url/lighthouse "target" an array, because there's no reason why a single website may not want many lighthouse reports. There are also other features attached to our lighthouse report runner internally that wouldn't make sense 1-to-1 in the open source version (such as authentication support), so it's an array of objects in the internal version today, and that's probably what we would want in the open source implementation, so that it can be expanded upon.

It seems like annotations are less flexible than the legacy catalog's was (strings only), so this may pose a problem for configuration, even though it's overall definitely a better idea to avoid the any-typed annotations... maybe some separate config file is needed and they Lighthouse catalog would need to pull it directly from git or something? @stefanalund can you help us figure out if there is some way of providing richer config to plugins per-component than annotations when a string doesn't do enough?

**Comment by stefanalund** [comment]
@fastfrwrd would you mind opening a new issue for that conversation?

**Comment by iain-b** [comment]
@fastfrwrd Thanks for the feedback! I can certainly certainly support an array of targets (array of url strings). I know this isn't as sophisticated as your internal version but it gets us closer for now. The annotation would be something like:
```yaml
  annotations:
    lighthouse.com/website-url: |
      https://roadie.io/
      https://roadie.io/backstage/plugins
``` 
I think something more complex could be achieved with a backend plugin but I'm aware I don't have much context as to what's required. 

I'm questioning what I've suggested for the UI above too. 
In terms of the tab content would it make sense to render a table like on the standalone lighthouse plugin page but displaying only those urls annotated on the entity?
For the widget though I think a more concise version of the data is needed  - perhaps just using status icons rather than trend graphs so it could be made to fit a narrower column.
@stefanalund Is there any prior art from the internal version you think might be useful?

**Comment by andrewthauer** [comment]
@iain-b - I'm pretty sure that annotation values can only be strings. This is how it works in k8 and I the backstage docs seem to also indicate this. Maybe this could tie into the idea around #2628 ?

**Comment by freben** [comment]
yeah that was one of those fancy multiline strings that yaml supports :)

**Comment by dtuite** [comment]
In the interests of getting something useful out into the open quickly, we should probably just support one lighthouse report per website for the moment and build on that going forward. Does that sound ok @fastfrwrd?

**Comment by fastfrwrd** [comment]
I think it sounds fine to start with one. It's worth keeping all this in
mind to help make decisions that avoid boxing us in going forward.

**Comment by iain-b** [comment]
Just going to leave a loom of what I've been working on https://www.loom.com/share/6c7e056c83a94043bd5091bd1fd34cdf. Any comments welcome. I'm just working through testing.

**Comment by stefanalund** [comment]
Left a comment in the PR. TL;DR I prefer a "rings" UI 😄
