### ISSUE TITLE
Fix microsite favicon's on Safari

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#3012]
## Expected Behavior

![Screenshot 2020-10-21 at 08 45 40](https://user-images.githubusercontent.com/190856/96683102-fce88700-1379-11eb-928e-c12ffdb70dd5.png)
![Screenshot 2020-10-21 at 08 45 59](https://user-images.githubusercontent.com/190856/96683105-fd811d80-1379-11eb-828c-01a84cd21378.png)

## Current Behavior

Old or missing favicon is shown ^

## Possible Solution

The microsite should use the images from:

https://github.com/spotify/backstage/tree/master/packages/app/public

**Comment by abhishekjakhar** [comment]
Could I pick this up?

**Comment by freben** [comment]
Sure!

**Comment by abhishekjakhar** [comment]
Safari does not support svg favicons, and we are using svg favicon. We are also having .ico format favicon, if I use that then the favicon starts appearing on the safari but .ico favicon which we are having is little bit different than the .svg favicon.

**Comment by freben** [comment]
Would you be able to generate a better ico from the svg? Or @katz95 do you happen to be sitting on an updated ico?

**Comment by abhishekjakhar** [comment]
I tried converting from svg to ico but the icon is not very good after conversion.

**Comment by stefanalund** [comment]
Logo assets can be found here: 

https://github.com/spotify/backstage/tree/master/microsite/static/logo_assets

**Comment by abhishekjakhar** [comment]
In the image given below, the left tab is having current favicon which does not work on safari and the right tab is having favicon which works on all browsers. But, the difference is the favicon in left tab does not have background. I am not able to generate a favicon without a background, because we are having PNG files which are very large in size and favicon generated from it is not in proper ratio.
<img width="387" alt="left-right" src="https://user-images.githubusercontent.com/19193724/97033733-6f778380-1581-11eb-913d-88ada802f61e.png">

**Comment by stefanalund** [comment]
I'm OK with having a favicon with background. Makes the situation better than right now at least :) Thanks for digging.
