### ISSUE TITLE
Groups/Users as owners of Components

### ISSUE THREAD

**Issue by jcarres-mdsol** [spotify/backstage#3050]
Now that Groups and Users can be defined, why not allow/require that the owner of a Component is a Group or User known by the system instead of an email which has no way to get extended with more information?

**Comment by freben** [comment]
That's been the intent the whole time actually!

A couple of puzzle pieces have had to land first - the [relations model](https://github.com/spotify/backstage/issues/1964), a way of uniformly expressing [references to other entities](https://github.com/spotify/backstage/issues/1947), the model for [organizational data](https://github.com/spotify/backstage/issues/1401) etc.

Things have been in a bit of an intermediate state for a couple of weeks but now it's time to settle the `owner` field as being an entity ref, to preferably a Group but otherwise a User, that should exist in the catalog.

**Comment by jcarres-mdsol** [comment]
Nice!

**Comment by benjdlambert** [comment]
@jcarres-mdsol can we close this issue now?
