### ISSUE TITLE
TechDocs: Fix broken page title while the docs are rendering

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#3099]
![Screenshot 2020-10-26 at 14 10 28](https://user-images.githubusercontent.com/8065913/97178429-c0f95b80-1797-11eb-8e45-6a51805d0d22.png)

## Expected Behavior

TechDocs generates documentation metadata for an entity from its repository. So, it takes significant time to get information like site name which goes into the title of the page.

While we are fetching the site name and other metadata, we already know the component ID. So, instead of having `[object Object]` in the page title, we can have the component ID there instead. And then, once we have site name, we can replace the page title with that.

## Current Behavior

Undefined values while the metadata loads.

**Comment by vividh** [comment]
I would like to work on this.

**Comment by OrkoHunter** [comment]
Great @vividh ! Assigned it to you

**Comment by vividh** [comment]
Thanks!

**Comment by vividh** [comment]
@OrkoHunter Made the changes in https://github.com/spotify/backstage/pull/3126. Do check it out.

The culprit LOC was the following in `TechDocsPageHeader.tsx`:

```tsx
<Header
  title={siteName ? siteName : <CircularProgress />}
  ...
  ...
```

Turns out the `Header` component uses `title` prop for the page title as well. But it also allows overriding it, so the following prop fixes it:

```tsx
pageTitleOverride={siteName || name}
```
