### ISSUE TITLE
plugin test and lint should be part of cli e2e test

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#312]
e2e test script: https://github.com/spotify/backstage/blob/master/scripts/cli-e2e-test.js

we want to make sure that lint and test commands run successfully in the newly scaffolded plugin

**Comment by mateusmarquezini** [comment]
Hi @Rugvip ! Maybe I can help with this! Any pointers to get started?

**Comment by Rugvip** [comment]
@mateusmarquezini Thanks, sure! I'm thinking we could make sure the `yarn test` and `yarn lint` commands run successfully inside the plugin folder, probably after we've stopped serving the app around here: https://github.com/spotify/backstage/blob/f60c5e417a6a67f081e187ef3d74486521f50abe/scripts/cli-e2e-test.js#L56

**Comment by mateusmarquezini** [comment]
Ok @Rugvip ! Thank you! ^^

Well, first of all I'm trying to understand how this script works and when it's called. I've ran the `yarn test` command, it executes pretty well inside these packages, except `yarn lint` that's giving me some errors. The point here is that this script executes in some time, right? When we stopped serving it, the commands `yarn test` and `yarn lint` should be executed, right?

**Comment by Rugvip** [comment]
@mateusmarquezini The script is executed here: https://github.com/spotify/backstage/blob/f60c5e417a6a67f081e187ef3d74486521f50abe/.github/workflows/frontend.yml#L42

You can also run it locally though, although it create a new plugin that you will have to clean up.

And yeah it takes a while to run :p

**Comment by mateusmarquezini** [comment]
Ok let me try this one, feel free to assign this issue to me :smiley:

**Comment by mateusmarquezini** [comment]
Hi @Rugvip ! 

One question, is there any pattern in the project when we create some component and its tests files? For example, if I create a component in my own plugin **ExampleComponent.tsx** its test should be written in a **.tsx** file (**ExampleComponent.test.tsx**) as well? Or this is just a good practice?

I have this question because I'm getting some type errors to fix the test execution when the cli creates the **test-plugin**, this line below for example:

`expect(rendered.getByText('Welcome to test-plugin!')).toBeInTheDocument();`

Is giving a type error when **expect()** method calls _toBeInTheDocument()_, because it's a TypeScript file.

The error is: 

`Property 'toBeInTheDocument' does not exist on type 'JestMatchersShape<Matchers<void, HTMLElement>, Matchers<Promise<void>, HTMLElement>>'.ts(2339)`

I could fix it changing the format file to **.js**, but I need to know if it's a pattern inside the project.

I looked for some use cases in the project using the method call _toBeInTheDocument()_ and there's no **test.tsx** file, only **.js** using it except for the plugins component, but I was confusing too because, when I run the tests inside the plugins folders, sometimes it passes and sometimes, no.

I think I could make this, changing the format file from **.tsx** to **.js**, even because it's something personal for the user these files in their plugins.

What do you think about this? Let me know your thoughts! :smiley:

**Comment by Rugvip** [comment]
@mateusmarquezini We want to keep tests in typescript too. Initially we'll probably want it repo-wide, but we won't require it in plugins, only in core code. The benefit of writing tests in typescript is that you end up testing the exposed types while you're writing the tests, which is something we definitely want for core packages.

Regarding the issue with `toBeInTheDocument`, that should be fixed in master afaik. Are you still seeing it if rebasing on top of latest master?

**Comment by Rugvip** [comment]
@mateusmarquezini Maybe you could open a PR with the current changes and we can iterate on the solution?

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini Maybe you could open a PR with the current changes and we can iterate on the solution?

@Rugvip it sounds good! First I'll make sure my branch master is up to date rebasing with the top master, after that, I open a PR.

**Comment by mateusmarquezini** [comment]
@Rugvip rebasing on top of the latest master fixed that problem I've mentioned. Thanks! :green_heart:
