### ISSUE TITLE
cost insights page not loading 

### ISSUE THREAD

**Issue by abhishekjakhar** [spotify/backstage#3134]
The cost insights page is not loading because we are getting currencies as undefined and we are trying to loop over the undefined using map method in CurrencySelect component.

## Expected Behavior

<img width="960" alt="cost-insights-page-fix" src="https://user-images.githubusercontent.com/19193724/97384497-cf5d8980-18f5-11eb-9d2c-2ec82f1dfad9.png">

## Current Behavior

<img width="960" alt="cost-insights-page-bug" src="https://user-images.githubusercontent.com/19193724/97384480-c967a880-18f5-11eb-9d57-ec0613627f02.png">

## Possible Solution

1. We could check for the presence of config.currencies and based on that we can render the `<CurrencySelect/>` component
2. We could use defaultCurrencies from types as fallback

## Steps to Reproduce

1. Run the project using `npm run dev`
2. From the side navigation select **Cost Insights**
3. You should see a white screen with error in console

## Context

I am looking to do open source contribution and I find this project very interesting

## Your Environment

- NodeJS Version (v12): v14.13.1
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7
- Browser Information: Google Chrome Version 86.0.4240.111

**Comment by ryanvazquez** [comment]
Nice catch @abhishekjakhar and thank you for your contribution!

The underlying issue seems to be that the export of defaultCurrencies from Currency.ts is returning undefined in useConfig - in fact, all non-type exports from type definition files are returning undefined - so the config state which is defined outside of the component, is being initialized incorrectly. At runtime when the component mounts, these references resolve but the Provider mounts with an incorrect state.

It appears this issue affects components who have similar dependencies on these non-type exports. Exports should always resolve, so the remediation for this will likely require migrating these non-types (enums, consts, etc.) to their own files.
