### ISSUE TITLE
[Phase 2] Scaffold a new micro service

### ISSUE THREAD

**Issue by stefanalund** [spotify/backstage#345]
Implement our internal use-case of allowing creation of new backend services from a template:

![1](https://user-images.githubusercontent.com/190856/77178005-c33f5d00-6ac6-11ea-8774-016f3d600a2d.png)

Demo video: https://www.youtube.com/embed/U1iwe3L5pzc

**Basic flow:**

- Select from a list of "templates", e.g. "Spring Boot Service".
- Provide basic metadata about the service.
- Select in which code repository the service should live in.
- Create a new repo and "hello world" service based on the selected template.

Longer term the micro service should be registered in an "inventory system", keeping track of what team owns it. This is out-of-scope for this Issue.

More background: https://backstage.io/blog/2020/03/18/what-is-backstage#1-creating-a-new-microservice

**Comment by fire** [comment]
Can you draft the list of the required and optional metadata fields?

There's also a list of operations that are automated in Jenkins? I use gocd, but that's obscure.

**Comment by mbruggmann** [comment]
@stefanalund This might be a detail, but have you considered not creating new repositories but a PR instead? That'd have a few advantages:
* Team members can peer review the changes before they get deployed to production
* Backstage doesn't need commit permissions to the master branch
* It's more natural for system- or mono-repositories that contain several components
* You get the same build, deploy and policy enforcement as any other PR, particularly if you add to an existing repository
* If there are warnings or errors, they more naturally occur in the PR flow instead of in Backstage

If the user wants to create a new repository, we could create an empty one with a PR against it.

**Comment by stefanalund** [comment]
@mbruggmann that sounds like an excellent suggestion to reduce the complexity/scope. 

> If the user wants to create a new repository, we could create an empty one with a PR against it.

Wouldn't this mean Backstage anyway needs credentials?

**Comment by stefanalund** [comment]
@jeffersongirao I know you had some ideas on how a new service creation could/should trigger events that other sub-systems could listen to, e.g. CI system.

Would you mind summarising your thoughts?

**Comment by stefanalund** [comment]
Link to video showing this use-case: https://www.youtube.com/embed/U1iwe3L5pzc

**Comment by jeffersongirao** [comment]
@stefanalund sorry for the long delay in answering this. Yes, I think it would be nice if we could model things here in an event driven way. That would allow people to hook on certain events to provide "backend" plugins in the most decoupled way as possible.

I was thinking about Kubernetes plugin model: there you have resources, a discrete set of events are emitted for CRUD operations on them, other events can also be generated tied to such resources by different applications. Then "plugability" into Kubernetes is achieved via the so-called Controllers/Operators acting as control loops on top of all those events. 

I'm not sure if the backstage backend plugins use case would be a stretch for Kubernetes Custom Resource Definitions but my impression is that we could even base everything on top of them.

As a side note I think it would be nice to use https://cloudevents.io/ to describe events in backstage land.

**Comment by mbruggmann** [comment]
@jeffersongirao What do you think about my proposal of making component creation PRs instead of deploying directly to production? Because in that case, you can rely on existing events (eg from Github) and CD pipeline tooling on merge rather than introducing a Backstage-specific event system for this.

**Comment by jeffersongirao** [comment]
Hey @mbruggmann! I think it makes sense to support both strategies when adding a new component. I think it depends a lot on what the organization using backstage will favor, creating an entire new repo or adding a PR to an existing one. 

I think that is an argument about detaching the concept of adding a component to backstage from actually creating a repository. In the event of a component being added to backstage inventory system, many things can happen in response to that, for example: a repository being created in Github (or a PR to a monorepo), dashboards being created in Grafana, alerts being defined in Prometheus, on call rotation added to Pagerduty (just making up things now :smile:) , all those things driven by discrete applications responding to the same event.

Perhaps you meant having the flow for adding components being SCM driven, adding a component definition to a repo in a declarative way instead of doing it via the UI. If so I like that idea too :)

**Comment by freben** [comment]
Making autoregistration work could be a separate optional thing either way, all else being equal. But I like that idea too.

In my mind, the scaffolder would essentially have many small single-purpose workers (pluggable, not knowing of each other) that collaborate to fulfill the parts of a "recipe". So the creation of a repo is one step that can be left out, and the generation of handlebars populated files is another, and the registration of the result in the inventory is another. Mix and match. And have a super basic state management and coordination for these workers.

Note that a worker is a code unit; I do not mean necessarily in terms of deployments (microservices), even though that would be one option. Many worker pieces could be co-hosted i a single service too (maybe even with the coordinator of so desired).

**Comment by mbruggmann** [comment]
I'm still wondering if the scaffolder should basically only be able to open PRs. Everything else would be SCM-driven (including keeping the inventory system in sync). That keeps the Backstage part much more contained. The flow would be something like this:

1. User goes through the new component flow in Backstage
2. If the user wants to create a new repo, an empty one can be created by Backstage (if we want to allow that).
2. Backstage opens a PR with the scaffolded code and configuration for the component. 
3. User reviews and merges the PR in the SCM
4. Update in the master branch triggers CD pipeline and SCM hooks
5. CD pipeline deals with deployment, allocating production resources etc (gitops style)
6. Backstage webhook gets triggered, updates inventory based on newest state in master

This has all the advantages mentioned above, primarily to minimize the permissions Backstage needs against the SCM and the production environment.

**Comment by freben** [comment]
How do you see this interacting with the creation of related resources such as a cloud project, database etc? In the cases where that could be relevant. Other processes that pick up on files created by this initial PR?

**Comment by freben** [comment]
Internally, as we dogfood this, we will want it to for example map a role to a project, and signals to evict caches etc.

**Comment by mbruggmann** [comment]
Yes, I think resources should be allocated in whatever process the company is using. Preferrably through the CD pipeline (like deploying manifests to Kubernetes, or applying Terraform).

**Comment by freben** [comment]
Hm. While I approve of the idea as such, I'm a bit hesitant, given how diverse the adopting organisations will be. Many likely won't already be webhook driven and ready to implement side effects (besides the basic putting of files in a repo) themselves elsewhere.

Would we still as a platform provide a good default place to put such reactive code? Imagine that we as Spotify were outsiders and adopting this. I want to evict caches, map roles to projects and register components as a side effect - would I typically make implementation changes in the internal registry and the caching backend, and make a new role registrator to listen to GHE, or would Backstage somehow help me with these concerns?

**Comment by freben** [comment]
Of course it could be argued that it could live inside the build step, executed by the CI/CD system - we could extend the Tingle base images or similar with bespoke code.

But what I'm reaching for, is that if we provide an inventory system, it could come with the plugin code that deals with registration into itself, and you would jack it onto your scaffolder as a oneliner. And you could write a mini plugin that does role registration that's internal to just your org and jack in that too - potentially all maintained in the same monorepo.

**Comment by mbruggmann** [comment]
Good points. I think we should have an answer to those, but maybe don't tie it strictly to the scaffolder?

It'd be nice to have an event stream where we can hook an external service into inventory updates. If the inventory listens to updates in SCM, this would get triggered if new components get created by the scaffolder. This is in line with what @jeffersongirao described as far as I understand. Maybe we could even support some type of Backstage backend plugin for this (subscribing to Backstage events). 

I'd just think that scaffolding is maybe not the right place to hardwire it, because you might have other paths to bootstrap components like forking repos, CLIs, copy-pasting etc.

**Comment by Rugvip** [comment]
@mbruggmann I think one thing to consider with scaffolding vs declarative approach is that the declarative approach is supposed to stay in sync, while scaffolding is a one-shot thing. That makes adding new templates to scaffolding waaaaaay easier, as there's no need to write logic for how to reconcile your desired state with the your actual state of the system. By creating resources through PRs, I think we imply a declarative approach, as it would be strange if changing those definitions did not get reflected in the system.

For a company that is in a state where they don't have either, standardised scaffolding will provide a lot more value for a lot less effort. You won't reach a golden state were everything stays in sync with the latest definitions, and you might want to move to a declarative approach over time. But that problem is much nicer than every team spinning up services in their own way, where every developer that peeks over the fence has to learn a completely new setup each time.

**Comment by mbruggmann** [comment]
@Rugvip Not sure I follow. As I see it, we are talking about three use-cases here:
1. Create components from cookie-cutters (or similar), through a UX flow in Backstage. The result should end up in the SCM of choice.
2. Keep the inventory service in sync with all components in SCM, including new ones created from 1.
3. Trigger other, possibly company-specific actions for "new" or "updated" components.

We can easily separate those. For 1, just push (or PR) to SCM. For 2, listen to SCM events (eg the Github webhooks) and check the repositories for what components exist. We could also batch index them periodically. For 3, provide a way to hook external services/lambdas/functions into updates of the inventory, through some event queue.

When it comes to resource management, that would still support a manual process (allocating resources in a proprietary or cloud vendor tool out of band), imperative (triggering a script for new components of certain types), declarative (managing resources as part of CD), or a mix of them based on component type. 

Does that make sense? Or did I completely miss another use-case here?

**Comment by benjdlambert** [comment]
Work is captured in the Scaffolder mileston
