### ISSUE TITLE
RFC: Backstage System Model

### ISSUE THREAD

**Issue by mbruggmann** [spotify/backstage#390]
We believe that a strong shared understanding and terminology around systems, software and resources leads to a better Backstage experience. This is a proposal for the basic entities we would model in Backstage, without going into how to implement this (yet).

We model our technology using these five concepts (further explained below):
* **Domains** are a high-level grouping of systems
* **Systems** encapsulate the implementation of APIs
* **APIs** are the boundaries between different components and systems
* **Components** are pieces of software
* **Resources** are physical or virtual infrastructure needed to operate a system

![Software Ecosystem Model_ Public Github version](https://user-images.githubusercontent.com/24575/77633084-39bcde80-6f4f-11ea-8251-f8df561a3652.png)

### Domain
While systems are the basic level of encapsulation for resources, components and APIs, it is often useful to group a collection of systems that share terminology, domain models, business purpose, or documentation, i.e. they form a bounded context.

For example, it would make sense if the different systems in the “Payments” domain would come with some documentation on how to accept payments for a new product or use-case, share the same entity types in their APIs, and integrate well with each other. 

### System
With increasing complexity in software, we believe that systems form an important abstraction level to help us reason about software ecosystems. Systems are a useful concept in that they allow us to ignore the implementation details of a certain functionality for consumers, while allowing the owning team to make changes as they see fit (leading to low coupling).

A system, in this sense, is a collection of resources and components that exposes one or several APIs. Components and resources in a system are typically owned by the same team and are expected to co-evolve. As such, systems usually consist of at most a handful of components. 

For example, a playlist management system might encapsulate a backend service to update playlists, a backend service to query them, and a database to store them. It could expose an RPC API, a daily snapshots dataset, and an event stream of playlist updates.

### Component
A component is a piece of software, for example a mobile feature, web site, backend service or data pipeline (list not exhaustive). A component can be tracked in source control, or use some existing open source or commercial software.

A component can implement APIs for other components to consume. It might depend on the resources of the system it belongs to, and APIs from other components or other systems. All other aspects of the component, e.g. any code dependencies, must be encapsulated.

### API
We believe APIs form an important (maybe the most important) abstraction that allows large software ecosystems to scale. Thus, APIs are a first class citizen in the Backstage model and the primary way to discover existing functionality in the ecosystem.

APIs are implemented by components and form boundaries between components and systems. They might be defined using an RPC IDL (eg Protobuf, GraphQL, ...), a data schema (eg Avro, TFRecord, ...), or as code interfaces. In any case, APIs exposed by components need to be in a known machine-readable format so we can build further tooling and analysis on top.

Some APIs might be exposed by the system, making them available for any other Spotify component to consume. Those public APIs must be documented and humanly discoverable in Backstage.

### Resource
Resources are the infrastructure a system needs to operate, like BigTable databases, Pub/Sub topics, S3 buckets or CDNs. Modelling them together with components and systems will better allow us to visualize resource footprint, and create tooling around them.

**Comment by freben** [comment]
This RFC does not yet mention entity ID spaces, and/or entities being sourced from several different ecosystems.

For example, if the data insights part of an organisation owns the concept and inventory of data pipelines, then would we require that their IDs do not clash with backend service component IDs? Or will they be namespaced to "kinds" or such, similar to k8s?

**Comment by mbruggmann** [comment]
@freben Good question, I don't have a strong opinion on that. How to manage the inventory and id spaces in a good way probably warrants a whole separate writeup. Do you want to propose something, given you have insights from how this works at Spotify today?

**Comment by freben** [comment]
Not quite yet, but when we start drafting the inventory part of Backstage, we'll have to tackle it. For now, this was more of a food-for-thought question.

**Comment by stefanalund** [comment]
I know this issue does not go into implementation details, but I'm adding this link here since people may be interested: https://medium.com/the-guild/graphql-mesh-query-anything-run-anywhere-433c173863b5

**Comment by yagnik** [comment]
This is AMAZING! Thanks for doing this. We have built something similar at Farfetch and would love to contribute here. Some questions:
- Would the "API" here only list networked services or would it include libraries ?
- At what level would we assign ownership (human or group or other machines maybe )? 
- Some prior art comes from cmdb which try to capture only physical resources, are we limiting backstage only to a system level ? 
- Are we considering capturing "data flow" and dependencies across domains and systems ?

**Comment by freben** [comment]
> * Would the "API" here only list networked services or would it include libraries ?

Internally at Spotify, we track a growing number of kinds of thing. The focus has been on software components of various types - services, websites, libraries, data pipelines, machine learning models etc. But it is also extending onto other types of software-or-system-like things, not necessarily created by us. For example, our internal Jira installation is owned and operated by a team, and that fact is also registered in our inventory. Same could go for third party external things such as Pagerduty, where we don't technically own the service as such but somebody owns the interaction, "problem space" and contracts etc - so that's registered as well.

What things are you most interested in inventorising?

> * At what level would we assign ownership (human or group or other machines maybe )?

Currently the owner field is just a string in the backing system, and it's up to other layers to enforce and/or validate it.

We have historically forced ownership to be on a team basis, so internally, to be considered well formed, our owner field should point to the LDAP name of a squad following certain rules. Some things may point to individuals and we don't reject that, but may inform you in the web interface that this is not normally allowed and you should change it. We are also expanding these rules internally to check that all component-owning teams are properly tied to a cost center to be able to do cost attribution etc. Being able to automatically track and analyse these things properly is one of the neat things of having such an inventory system.

We realise that these types of business rules may be different for each company that adapts Backstage and would need to leave it configurable or pluggable in some way in the open source product. We'd be interested to hear what your ideal setup could look like.

> * Some prior art comes from cmdb which try to capture only physical resources, are we limiting backstage only to a system level ?

Could you expand on this question a bit? The main target for this inventory has not historically been physical things, but maybe it could be relevant to expand the Resource concept to that?

> * Are we considering capturing "data flow" and dependencies across domains and systems ?

That is absolutely a very interesting thing to track. An inventory system could perhaps help store references between components and resources, but probably mostly for very static things.

Internally, we have usually deferred the indexing of more dynamic relationships, to runtime analysis systems. I.e., they would probably not be managed or stored by the inventory system but by other specialised services.

One such example would be service -> library dependencies; this would likely be burdensome to maintain manually, and besides, it will change over time from version to version of the service. So that may better be served by the CI/CD system having a post-build analysis step in it. A specialised service could ingest and serve that information.

Another example may be what pubsub topics that are consumed by services. The best source of that would be tracing the actual usage by live services, or perhaps by analysing the RBAC setups for service accounts that the live services use. A specialised service could deal with that too.

See where this is going? It's a super interesting problem space, and we hope to make use of current and future open source offerings to let you have a rich and vibrant data set to consume in Backstage and display in all of the relevant service views, maximising insights into the ongoings of your software fleet. But the data may come from many places and be aggregated in various nice ways. Internally we have a GraphQL service that helps with this.

**Comment by mbruggmann** [comment]
> Would the "API" here only list networked services or would it include libraries?

Likely both. As per @freben's answer, we track many different types of software components, but think it's particularly useful to identify APIs that form boundaries between systems. The need for code interfaces as APIs has also come up in internal discussion (eg in application frameworks or large applications such as our mobile clients), I'll update the issue with a formulation that is more inclusive for that.

> At what level would we assign ownership (human or group or other machines maybe)?

I'd propose that all entities in this model have an owner. What form ownership takes might be company-specific, in Spotify's case we would want to verify that they are valid teams in our internal LDAP.

> Some prior art comes from cmdb which try to capture only physical resources, are we limiting backstage only to a system level?

No, we think the `Resource` type described here would be suitable for tracking physical resources. This is probably more useful for longer-lived ones (eg servers). As we are fully cloud-based at this point, it would be great to learn more about what types of resources you'd like to track.

> Are we considering capturing "data flow" and dependencies across domains and systems?

Those things would make great Backstage plugins :) At this point, we'd start with having a central inventory service that keeps track of what entities exist. We can then attach additional information at runtime, from offline analysis, or from static metadata in source repositories.

**Comment by RoyJacobs** [comment]
This is a really simple but powerful model, very interesting.

At bol.com we've been [prototyping a service called Katalog](https://github.com/bolcom/katalog) specifically to host API specifications (i.e. Swagger or OpenAPI specs, but potentially any kind of spec, like gRPC). The idea is that teams can associate different version of specs to a service, notify users of deprecations, etc. Consumers of a service can retrieve an API spec based on a NPM/Maven style glob (i.e. "give me version 2.x of service Foo"). It's not yet deployed though, but I think the core concepts could be very suitable for inclusion in Backstage in some form.

So, I’m not completely sure yet how much of Backstage is going to be “just” a frontend on a number of disjunct backend systems, or whether it will be hosting a bunch of data itself as well. The reason I ask is that currently Katalog is doing a bunch of things that ideally we’d want to centralize: User/group management, management of “namespaces” and “groups” (ideally replaced by the system model), mailing, notifications, scheduled jobs, etc. It feels like it would be very useful if a lot of these things could be centralized since a lot of Backstage plugins will want to re-use this functionality.
 
In fact, you could argue that having a “watch” function in Backstage to get notifications about interesting things happening to a certain system would be very nice: It could aggregate a bunch of interesting events from multiple plugins and push them to the user (e.g. via daily mails or whatever). This is now a feature in Katalog, but why limit it to just changes in your API specs?
 
So the question for me now is: Does this fit in your vision? Can Katalog be focused on just “attaching” API specifications to the API part of your system model, and can Backstage do all of the overall orchestration? Would Katalog even exist as a product as it is now, or would we be able to make it much more lightweight? Is a Backstage plugin also a server component or just a frontend component?

Anyway, I'd be interested to hear your thoughts on this here, on in a separate issue perhaps.

**Comment by stefanalund** [comment]
@RoyJacobs there are a few things to unpack here :) 

From an API use-case perspective we envision two different ways for people to use Backstage to explore APIs:

1) **Inspecting the API of a backend service.** The current way we do this at Spotify is described in [this short video](https://www.youtube.com/watch?v=vcDL9tOv7Eo). Currently we only support REST/OpenAPI but I think at least gRPC should be supported as well. I imagine this use-case will become part of Backstage when we get to [Phase 2](https://github.com/spotify/backstage/milestone/4).

2) **Exploring all APIs in an organisation.** In 1) you first need to know the name of the service to find its API. This limits discoverability and I think a _separate plugin_ should expose a "API explorer" where a user can browse and find all APIs inside an org.

Nr 2 requires a central repository of all the APIs. This is not something Spotify has today, but if I'm understanding correctly, this is one of the use-cases for Katalog. If this is the case and you are interested/willing to help integrate Katalog as a plugin in Backstage that would be great. As you say, it might be better to create a separate issue in that case.

Having a watch- and notification system sounds useful for the broader Backstage platform -- not just tied to one specific plugin or use-case. Feel free to create an issue for it as well.

**Comment by RoyJacobs** [comment]
I think Katalog could be quite suitable for this, but I'd prefer to make it somewhat more lightweight than it currently is. The two main things it currently is managing itself, but I'd rather keep out of scope, is user/group management and the hierarchy of the APIs (i.e. to which system does this particular API belong).

Would it make sense to create a tracking issue to discuss a "Backstage system model API" that other services, like Katalog, would consume? This would make Katalog a "Backstage-only" system, effectively (well, in its initial revised version anyway), but that's fine for our needs currently.

For now, user management could be out of scope, under the assumption that all APIs within a company could be considered "public" within the company.

**Comment by stefanalund** [comment]
@RoyJacobs put together an issue outlining how we envision API documentation from a user perspective, i.e. as exposed in a plugin: https://github.com/spotify/backstage/issues/627

I still think there is a need to clarify how this would technically fit together with the contents of this RFC. Probably best handled as a separate issue.

**Comment by aexvir** [comment]
I really like the idea to have a unified layer where all the plugins could read from. I'm thinking about something like what [Gatsby.js does](https://www.gatsbyjs.org/docs/recipes/querying-data/), where it consumes inputs and it exposes a single GraphQL API where any page can consume potentially any data it wants, by making GraphQL calls.

The [suggestion](https://github.com/spotify/backstage/issues/390#issuecomment-604638727) of using something like GraphQL Mesh makes total sense to me, as it would be simple to just stitch together multiple backends under a single layer that can be consumed from any plugin, making integrations between plugins really nice. And potentially releasing independent backends, that will feed data to the GraphQL layer, and plugins, that will consume it.

**Comment by meledin** [comment]
One of the things I've encountered a lot with microservice work is data model. Namely, the number of data models scales at a rate of Ω(#services), barring an external force. Thus, within certain solution areas, I've leveraged shared data models, where a master specification is used to hydrate the data model across all users (thus, multiple APIs expose/reuse the same data model). I assume that's something encountered here as well, since the **Domain** concept discusses entity models; but it's non-obvious to me where those entity models would reside below it. Are they part of the domain, or component, or something else?

Another class of entities from the screenshots/videos that's at least hinted, is monitoring, metrics, operational data and logging. Are they treated on a Service level, or sub-levels (component/resource)? Both component/resource _do_ have individual metrics (especially if resource is DB/cloud resources), but for someone external to the team maybe only the Service metrics are really interesting for an overview (is it up? where is it up? expected performance?). 

As for APIs themselves, following the diagram, while it's technically true that an API is implemented by one or more components, it may be relevant to declare/track _accessed using_ as an item. Sometimes, it may be that a collection of APIs may be implemented by a number of components, but accessed through a single service (Spinnaker orca == implementation, Spinnaker gate == access) to apply access control and authorization.

**Comment by freben** [comment]
Remaining work: create documentation about what the metadata structures look like, after setting #983

**Comment by lawrencejones** [comment]
Hey all! Thanks for putting so much work into making these concepts clear, it's so key for anyone trying to adopt backstage in their own company.

One thing I'm missing from the concept diagram presented here is the idea of an application environment. We tend to model our applications as services, each of which runs several environments.

I'm not clear how this type of concept works in the backstage catalog entity model? Do we assume each environment is modelled as a separate component? Grouped within the same or a different system/API?

I might be missing something here but I think some additional clarity around this area would be really useful. I suspect a lot of places think in terms of 'service+environment' combinations, and would be useful more generically.

**Comment by freben** [comment]
The initial limited scope of the catalog (with a focus on Component) has now been merged and settled in documentation, so closing this issue.

**Comment by freben** [comment]
@lawrencejones Hi! Thanks, keep us updated if there's more we could do to address or document things that you run into.

Regarding your question:

If I understand your situation correctly, that sounds like still just one Component in our parlance. As in, it is one set of source code, consistently owned and maintained by a group of people. The build and deployment strategies are a completely separate dimension to us, and those may well be reflected in the Backstage user interface as well, but under the "umbrella" of that one component.

For example, internally, our deployment/rollout system has support for both canaries and autoscaling and various other features, but those are managed by services for which there exist Backstage plugins to modify or track their behavior. For example there is a button to roll back to a previous known good build artifact, or to promote from canary to full deploy etc. Those are the concerns that the engineers that own the component need to interact with directly and effectively, so that's what is presented to them. The component page has tabs on its side to navigate between the views for build logs, deployment, API overview, quality metrics ... and all of the other infra for which this group of pages represents the glue.

But the component is referred to uniquely across all of this.

**Comment by lawrencejones** [comment]
That all makes a lot of sense @freben. Still trying to understand how to model our systems in this language- thank you for your clear explanation!

**Comment by freben** [comment]
@mbruggmann An evemt stream output (perhaps as a pubsub topic) from a service would fit neatly within the API concept, would it not? Or does it even deserve special treatment?

**Comment by mbruggmann** [comment]
@freben Agreed, it'd be nice to model event streams as APIs. Then Backstage could list all available pub/sub topics with their payload schemas 😍

**Comment by RoyJacobs** [comment]
There is an effort to standardize these kinds of API through [Async API](https://asyncapi.io/). I'm not sure if this is too detailed for you, but it could be an inspiration for the model maybe?
