### ISSUE TITLE
RFC: Service discovery backend

### ISSUE THREAD

**Issue by aexvir** [spotify/backstage#454]
## Context
In our company we developed a really similar platform as `backstage`, and in our case we started by taking the services as the root of all connections. If we want to start considering `backstage` as an option, having a backend able to discover all our services it's a must.

## Feature Suggestion
We have two ways of adding a service, by manual input, using some forms, or by detecting a `.yml` file in the root of the project, where all the info regarding the service is defined.

This feature request should be about the second part only as of right now. Not sure how manual input is seen in other environments different than ours, but technically it shouldn't be hard to do either.

## Possible Implementation
To make it flexible and easy to integrate, I'd like to propose having a backend that could be configurable in two ways:

1. Regex/Glob for descriptor file
2. Schema of descriptor file

I'm suggesting a regex/glob for identifying the descriptor file because based on our experience, it's not easy to achieve a consensus about where things have to be stored. And I'm also thinking about monorepo support, where there could be a descriptor file inside every service in the monorepo if needed.

Regarding the schema, I'd like to use something like [JSON Schema](https://json-schema.org/) to define it. The question here is if there should be a minimum of fields required, which I'd say yes, to make integration with other backends/plugins easier.

Maybe just an ID? That should be enough to query more details about the service whenever needed, but in that case I'd probably leave it outside of the schema, like we have, and autogenerate it.

Not sure about this, let me know what do you think.

To finish, I'd like to post our current JSON Schema for identifying services:

```jsonschema
    type: object
    properties:
        type:
            type: string
        name:
            type: string
        owner:
            type: string
        impact:
            type: string
            enum: ["profit", "customers", "employees"]
        status:
            type: string
            enum: ["beta", "production", "deprecated", "discontinued"]
        docs_url:
            type: string
        slack_channel:
            type: string
        sentry_project:
            type: string
        sonarqube_project:
            type: string
        pagerduty_url:
            type: string
        tags:
            type: array
            items:
                type: string
        environments:
            type: array
            items:
                type: object
                properties:
                    name:
                        type: string
                    dashboard_url:
                        type: string
                    service_urls:
                        type: array
                        items:
                            type: string
                    health_check_url:
                        type: string
    additionalProperties: false
    required:
        - type
        - name
        - owner
```

**Comment by aexvir** [comment]
In this case, we would like to develop such backend, and make it available also as open source software. We would do it most probably in Go, probably not important, but I just want to know if there is some concern about this choice.

**Comment by mbruggmann** [comment]
@aexvir Agree that we should do something in this space. We started discussing the model we want to use in this issue: #390. 

One thing I'm curious about: How do you see this interacting with source repositories, eg Github/GHE or Gitlab? Because I think these as very related. We'd have some type of service with a REST or gRPC API that stores what entities exist, and some integration with version control that would track changes in master, pick up on those files as you describe, and push them to the service for storage? Like a [Github app](https://developer.github.com/apps/)?

**Comment by aexvir** [comment]
Hi there @mbruggmann 

Yes, the relation between repository and service is essential, and it's also core of our implementation. What we have is a django app, with a periodic task that scans all the repositories of our internal GitLab and updates the info in its own PosgtreSQL database.

That can be enhanced by using [system-level hooks](https://docs.gitlab.com/ee/system_hooks/system_hooks.html), that would trigger the backend ad-hoc to register a new service (e.g. on project creation), and CI/Actions/jenkins/whatever jobs if we want to avoid periodic crawling.

**Comment by dtuite** [comment]
@aexvir when you first implemented your Backstage-like internal system, how did you get all teams to agree on the metadata schema and ensure that all the teams implemented it across the company?

How do you ensure that the metadata is correct and fresh? Are there validation steps or systems which ensure people are periodically updating it.

**Comment by Rugvip** [comment]
@dtuite we just started up a discussion about the metadata format in a separate issue as well if you wanna have a look: https://github.com/spotify/backstage/issues/767

**Comment by freben** [comment]
@dtuite I can speak for us at Spotify at least. Here, the format was essentially dictated by the infra team that owns the internal inventory service. It has _very_ few required fields that are very understandable by humans, so running stale isn't often a thing. And then there's a random bag "put whatever you want in here" `fact` key as well, for auxiliary data.

The inventory system automatically keeps itself up to date with changes in git. If there are errors or conflicts, it keeps serving the old valid version and informs you that you have issues with the file.

Sometimes the `facts` random bag has been overused or kind of even abused. But it's not been a major issue.

Uptake of this service descriptor format has been stellar, partly because of our company focus on the golden paths, as we call them. When you create a new "thing", for example a backend service, you do it through Backstage. It scaffolds a bare bones thing for you according with all current best practices, and that includes this descriptor file, which is automatically registered for you. Another reason the uptake is great, is that it's the gateway into Backstage. You don't get all the goodies unless you register your thing in the inventory. We even have a little wizard that makes it trivial to generate just that descriptor, if you have an old and not-yet-inventorised thing.

Some attempts have been made to extend the core fields or rearrange things over the years, but they usually don't fare well - getting the bare essentials right is important.

**Comment by dtuite** [comment]
@freben Appreciate the insight.

> Uptake of this service descriptor format has been stellar, partly because of our company focus on the golden paths, as we call them. 
> Another reason the uptake is great, is that it's the gateway into Backstage. 

Yeah we did something similar in Workday. Basically if you don't have your metadata in the catalog you can't get your stuff into production.

Backstage didn't exist at the very start of Spotify though (correct me if I'm wrong please!). So there must have been some moment where there were N teams building stuff but 0 had metadata in their service repos. The infra team invented the metadata schema, but then they had to convince people to use it. How did they then convince all N teams to add the metadata to their repos? There must have been some transition period where things which were already in production had metadata retroactively added to them.

In our case, we essentially put 10 people in a room for a few hours and they manually created metadata for (almost) every service in the system in order to bootstrap it to critical mass so it could start providing value. It kinda sucks but it worked.

**Comment by aexvir** [comment]
@dtuite It wasn't really consulted with anyone, our team is the one centralizing this efforts and we just decided what was the minimum to cover. With time we have expanded it a couple times based on general interest, like when we added environments.

Usually this additions are optional, so it's not a big deal if the teams don't have them set up, but for cases like in the environments additions, we prepared a migration that would move every service's "environment related" fields under a new environment called "default" for example, to avoid friction.

**Comment by dtuite** [comment]
@aexvir Thanks Alex. Sounds like what we did, used a highly motivated team to centralize the effort to get it done.

**Comment by stefanalund** [comment]
Time to close this issue now that we have decided on the format? 

https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md

@freben

**Comment by freben** [comment]
Agreed. @aexvir please have a look at the ADR if you have the time. It leaves a few degrees of freedom open:

- The spec for Component is not set in stone yet. It just has a type field now. If we feel that there are more fields that we can place there, that are NOT a good fit for labels or annotations, we can discuss putting them as part of the core spec.
- The labels are a possible place to put information directly related to the entity, like your `impact` and `status`. We will be looking eventually at a standard set of "well known" labels that both humans (in search filters etc) and plugins that consume entities can rely on, but for now it's left open.
