### ISSUE TITLE
Investigate: Remove @storybook/addon-storysource as a core dev dependency

### ISSUE THREAD

**Issue by OrkoHunter** [spotify/backstage#557]
## Feature Suggestion

In https://github.com/spotify/backstage/pull/548, we added a storybook addon which shows the code of components in the storybook. However, Storybook does not compile unless the addon is installed in the `packages/core` package. Since, we removed storybook package out of `packages/core` into `packages/storybook`, it would be nice to avoid this dependency.

Investigate if it is possible to show components' code in storybook without `@storybook/addon-storysource` as a dev dependency in `packages/core`.

## Context

See [this review comment](https://github.com/spotify/backstage/pull/548/files#r407792660) for more context.

**Comment by OrkoHunter** [comment]
@stefanalund @Rugvip Please assign appropriate labels 🙏

**Comment by Rugvip** [comment]
The line in question: https://github.com/spotify/backstage/blob/dd1ef4eda03d0203338bd632c728d2033434ca67/packages/core/package.json#L47

**Comment by braulio-balanza** [comment]
Wouldn't the import be needed because .storybook/main.js loads all files from /core/src?
https://github.com/spotify/backstage/blob/cf30e4615d4c6c2ffde5b969684e634cb73549a8/packages/storybook/.storybook/main.js#L4-L7 https://github.com/spotify/backstage/blob/cf30e4615d4c6c2ffde5b969684e634cb73549a8/packages/storybook/.storybook/main.js#L18
Would moving all the .stories.tsx files to storybook/src and then importing @backstage/core as a dependency in storybook/package.json be preferable?

**Comment by OrkoHunter** [comment]
Thanks!

> Would moving all the .stories.tsx files to storybook/src and then importing @backstage/core as a dependency in storybook/package.json be preferable?

I believe it is preferred to keep components and their stories in the same directory. This helps in making sure the stories and the components are in sync.

**Comment by braulio-balanza** [comment]
Could copying the .stories.tsx files from core/src to storybook/src whenever running the ```yarn storybook``` command work?

**Comment by OrkoHunter** [comment]
Oh, interesting.
