### ISSUE TITLE
[Plugin] Kubernetes

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#632]
## Summary

- A plugin to see the current state of your Kubernetes clusters that you have
- Be able to inspect the clusters, active instances on a cluster level
- Be able to see active deployments and map those to components in Backstage

## Project website (if applicable)
https://k8s.io

**Comment by stefanalund** [comment]
Related project: https://github.com/hjacobs/kube-web-view

**Comment by braulio-balanza** [comment]
I think I could take a shot at this one!

**Comment by stefanalund** [comment]
Great, I’ve assigned you!

**Comment by soapraj** [comment]
Hey! @braulio-balanza - awesome! that you are picking this up 👍 

Can you share some details on the design and interactions before you start with the implementation? It would help us iterate on ideas and design

cc @katz95 for design inputs

**Comment by braulio-balanza** [comment]
That actually sounds great! Some guidance would be really good! 

So basically the way I was thinking to implement the plugin was using the new inventory plugin as an example and have two plugins

```
plugins/
    kubernetes-frontend/
    kubernetes-backend/
```
I haven't given much thought about kubernetes-frontend, but for kubernetes-backend it would basically be an express router using the [kubernetes javascript client api](https://github.com/kubernetes-client/javascript)  hooked to the packages/backend server. Then the kubernetes-frontend plugin would just load the data from the backend server. 

I am creating a backend because trying to use the kubernetes api from the frontend gives me a bunch of errors (CORS request denied). But if there is a way of not requiring a backend, it would be much simpler.

**Comment by Escalion** [comment]
My feeling is that it is actually better to have a backend and a frontend for this, as opposed to rolling it into one frontend plugin.
At least by separating the concerns, you can protect the resource, in this case, a K8s cluster 🤕.
It also allows for user permissions (if this is planned? @stefanalund) and the ability to show/hide resources on a per-user basis without exposing 'everything else' (tm)

**Comment by freben** [comment]
Agreed, a backend probably makes sense here.

Yes we are planning to lift over a user identity concept to Backstage, adapted from the internal project. The details of that design aren't set yet.

As to how that design affects what a kubernetes plugin shows - that's an interesting question. Any ideas here?

One way could be to go from user identity -> list user's owned components in the inventory -> list kubernetes resources mapped to those components.

**Comment by mclarke47** [comment]
What about something like this:

![kubernetes backstage plugin](https://user-images.githubusercontent.com/6514980/87429872-53586380-c5dc-11ea-8518-5a3b9208e45b.png)

**Comment by Rugvip** [comment]
@mclarke47 Looks like a plan :grin:

It's probably good to start off with having #1 be a manual step, as in an [annotation](https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md#annotations) in the entity description. I'm thinking the entire cluster name + deployment namespace + name. Then we could probably go from there and figure out how to remove that manual step, e.g. populating it as a part of the deployment process.

For #2 I'm hoping we'll be able to stick to limited read-only credentials all the way to the client talking to the k8s provider, so that we don't need to store any too sensitive credentials in the plugin backend. If we end up needing to do that we might want to immediately make that a separate service that's a bit more hardened. Other than that I'm not sure we need to support any particular access control for now, as I don't really think deployment status of the service is more sensitive than the rest of the information about it. We're gonna end up wanting to know about the ownership and access of the user in the future though, so still something to prepare for.

Regarding #3, it would be pretty awesome if we could rely on the k8s watch APIs + SSE :>

#4 is problematic, @katz95, halp! 😁 

Overall though this seems like something to make part of https://github.com/spotify/backstage/milestone/14 :grin:. We're already thinking about using a k8s deployment for that just to enable some more dogfooding.

**Comment by braulio-balanza** [comment]
Hey, that is super cool @mclarke47. I have mostly focused on 3, although given the situation I haven't been able to focus as much as I would want on it. How could be the best way to share with you what I have so far?

**Comment by mclarke47** [comment]
@braulio-balanza perhaps a Draft PR?

**Comment by mclarke47** [comment]
I'm going to try to lay the foundations for this in the next week or so, in line with https://github.com/spotify/backstage/issues/632#issuecomment-658172675

**Comment by mclarke47** [comment]
Just confirming with my team how we will do this and we're hoping to get started ~21st

**Comment by mclarke47** [comment]
Opened an RFC over at https://github.com/spotify/backstage/issues/2857
