### ISSUE TITLE
design request: CodeSnippet component in shared

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/backstage#660]
## 🗒 General

Since we have a bit of inconsistency on how this goes internally, we ought to use this as an opportunity to expose a standard CodeSnippet component which honors dark mode, handles very large code snippets well, and supports syntax highlighting.

## 💻 Usage

Sometimes, code snippets will need to appear in a plugin, for example when the component author needs to communicate a code snippet that the user needs to see contextually, rather than linking out to some docs where it's simpler to correctly format the code. Without having this, people (like me!) will use `<code><pre></pre></code>` to do this, which will not include syntax highlighting and will be less good than something more thought out.

## 📐 Specs

- should have toggleable line numbers
- should have automatic darkmode support
- should probably be a thin wrapper around some popular open-source view

## 🔮 Future

Eventually could be a jumping-off point for code playgrounds inside of Backstage, which is a feature we don't currently have but very much could.

**Comment by NWCalvank** [comment]
I'd like to pick this up if no one else has claimed it.

Since this would be my first contribution here, I spent a little time this afternoon getting a very basic POC working in storybook -- largely just to make sure I wouldn't run into environment issues after putting my name on this task.

In doing so, I came up with two questions:
- Should the toggleable line numbers be toggleable for the end user (via the UI), or toggleable with respect to the parent component (via the callsite in-code)?
- This was the most popular and recently-supported code snippet I was able to find, given some initial research: https://www.npmjs.com/package/@atlaskit/code. Any objections to it? It seems to support the features that you're looking for.

Let me know! Thanks

**Comment by stefanalund** [comment]
Thanks @NWCalvank I assigned you!

> Should the toggleable line numbers be toggleable for the end user (via the UI), or toggleable with respect to the parent component (via the callsite in-code)?
I think we can start simple and not make it configurable for the user.

> This was the most popular and recently-supported code snippet I was able to find, given some initial research: https://www.npmjs.com/package/@atlaskit/code. Any objections to it? It seems to support the features that you're looking for.
We don't have strong opinions on this. Try that one out and design the reusable component in a way that the underlying library could be replaced (if possible).

**Comment by stefanalund** [comment]
Closed in https://github.com/spotify/backstage/pull/803
