### ISSUE TITLE
[Plugin] TechDocs / Docs-like-code

### ISSUE THREAD

**Issue by leemills83** [spotify/backstage#687]
## Summary

Add easy to use technical documentation plugin to Backstage. Some inspiration can be found from our internal technical documentation:

![Screenshot 2020-04-30 at 17 02 45](https://user-images.githubusercontent.com/1236238/80726945-60010b80-8b05-11ea-8c27-d07d6719842b.png)

## Context

TechDocs makes it easy for you to make your team’s technical documentation available in a central place (Backstage) for other teams to discover. Treating documentation as code, you produce documentation within your software development workflow. You follow a few simple conventions and your documentation appears in Backstage instantly.

**Comment by stefanalund** [comment]
Since TechDocs is an internal name I think it would be better to name this issue something like “Docs-like-code” or just “Technical documentation”. 

I also look forward to seeing what different pieces are required behind the frontend for this plugin to work 😀

**Comment by andrewthauer** [comment]
I've been thinking and experimenting a lot with a `docs-like-code` approach recently. I'm curious on the scope of what this plugin might provide though.

I know Spotify uses `mkdocs` internally. I looked at a lot of different static site generators and also settled on `mkdocs` because it seemed to provide the least configuration setup required for teams to use in their projects. In fact I've been able to hide it within the CI pipeline entirely so folks can focus on just writing docs and rely on conventions.

That said, I do think that any solution here should be agnostic to the tools to generate documentation (if possible). Integration with any existing tools that an organization may be using would be key for larger adoption.

Here is a list of "potential" areas of scope I see for this plugin:

- A catalog / inventory system that tracks various documentation sites that might be generated by different teams, repositories, etc.
- The front-end plugin that handles routing & rendering of documentation sites.
- A back-end search service that proxies search queries to something like elasticsearch. The results would then need to be mapped to appropriate deep links on different sites (which the frontend would need to handle routing for)
- Some sort of system that can update the search index when docs sites are updated/published.
- Common tooling to generate sites that "conform" to the contract that will work with the plugin tooling, catalog, index service etc.

Some other features that seem really useful would be:

- Analytics tracking.
- Knowing when documentation has been updated and pushing that up to.
- Ability to annotate & edit docs or easily when reading.

Also curious where the line is drawn for tools that content creators will be using to create documentation? Tools can be very opinionated and highly dependent on individual workflows & processes. However, it feels like the content creation experience is a key ingredient in how it might relate to the consumption of the content.

PS - Very excited about this plugin 😄

**Comment by SpamapS** [comment]
I don't know if this is directly related, or something that would be a separate feature or part of this, but a really neat thing that the Rust community does is that they run the example code snippets in their technical docs as tests. This prevents the problem of "the example doesn't work anymore" and is especially good for avoiding API breakage.

https://doc.rust-lang.org/rustdoc/documentation-tests.html

**Comment by Rugvip** [comment]
@SpamapS, yep! same thing in Go, https://golang.org/pkg/testing/#hdr-Examples

Never seen it implemented in JS/TS though, probably trickier since it's a dynamic language. It's a neat idea though.

Did just find this: https://github.com/yamadapc/jsdoctest :grin:

**Comment by stefanalund** [comment]
> A catalog / inventory system that tracks various documentation sites that might be generated by different teams, repositories, etc.

@andrewthauer I think we should follow the same model we use inside Spotify; i.e. treat documentation as yet another piece of software that is stored in the [Software Catalog](https://github.com/spotify/backstage/milestone/4).

In such as setup there are two categories of documentation:
1. **Docs only** - stand-alone documentation site
2. **Docs with code** - documentation living together with an existing software component, e.g. a backend service or website.

**Comment by andrewthauer** [comment]
> In such as setup there are two categories of documentation:
> 
>     1. **Docs only** - stand-alone documentation site
> 
>     2. **Docs with code** - documentation living together with an existing software component, e.g. a backend service or website.

@stefanalund - These make perfect sense to me and is how I've also been looking at it.

I wonder if there might be room for a 3rd more abstract option such as `external` docs? I suspect many organizations will still leverage other documentation systems/processes along with backstage (either transitioning or permanently). I have no idea how this would work, but being able to somehow integrate existing documentation systems into a central place like backstage could both help encourage a `docs-like-code approach and avoid yet another documentation tool/process being introduced.

**Comment by stefanalund** [comment]
@garyniemen @emmaindal time to close this one?

**Comment by garyniemen** [comment]
Not quite. But soon. Our [v1 milestone](https://github.com/spotify/backstage/milestone/16) is an alpha version of TechDocs that works end-to-end. We have set a due date of 28 August.

**Comment by OrkoHunter** [comment]
With TechDocs v1 launched and progress being tracked by Backstage documentation, I think it is okay to close this issue. cc @spotify/techdocs-core @stefanalund @leemills83

**Comment by OrkoHunter** [comment]
Please re-open if you feel so. 🙇
