### ISSUE TITLE
catalog backend: implement refresh loops

### ISSUE THREAD

**Issue by freben** [spotify/backstage#771]
Implement the logic of the backend service that keeps components refreshed from descriptor files in a version control system.

## Background

The corresponding service at Spotify stores the latest known good version of component files in a data store, and continuously attempts to refresh them with new data from our GitHub Enterprise, via polling. It also keeps track of the current status of this refresh loop per component, along with errors encountered. This status is part of the response when fetching components.

The first version of the catalog service will do the same. Push based or event triggered updates will come later.

## Some Questions

- As a location is registered, shall an initial refresh attempt be made, and the location registration fail if the refresh fails?
- How will later failed refreshes be handled? What metadata about the errors shall we store and how are they communicated to callers or component owners?
- What version control systems shall we support? Presumably at the very least github and gitlab. Shall this be pluggable?
- How shall we handle authentication for requesting data from the version control system? Can we initially use `/raw/` or similar browser endpoints, or should we for example require that the user supply a dev token to pass to API calls?
- How shall we handle rate limits and other exceptional states when doing refreshes?

**Comment by mbruggmann** [comment]
Have you considered using a push model instead of refreshing in a loop? Like having a CRUD API that takes the full values of the "yaml files", then having a Github Action or similar to push updates from repositories? It has a few advantages I think:

* It gives us a natural place to read and transform existing metadata files. So if I already have some metadata in my repositories, I can do a script to transform that into the Backstage format and submit it to the API (periodically, or from CI) rather than hooking it into the Backstage refresh loop.
* Backstage doesn't need the permissions to check out the code.
* We isolate the VCS-specific part of the code, so it's easier to replicate for other providers such as Gitlab.

The downside is that we won't be able to notice if things go stale, and we'd need to verify that the caller is authorized to update this part of the inventory (although that we probably need anyway).

**Comment by freben** [comment]
Yeah. We've discussed back and forth with a lot of ideas, and the immediate take is, since the internal inventory model has served us so well, we would do best to implement that quickly first, to unblock further iteration and invention (by both us and others) on top of that.

This does put some pressure on getting the design right now, so it's extensible.

**Comment by mbruggmann** [comment]
Fair enough, I don't think this is irreversible in any way so we can start with whatever makes most sense short-term.

**Comment by freben** [comment]
This already has a basic solution, and more sources and metadata are being added step by step. I consider this ticket solved, with the scope it was given.
