### ISSUE TITLE
[Plugin] New Relic

### ISSUE THREAD

**Issue by palmerj3** [spotify/backstage#824]
## Summary

A plugin that shows the most important data from [New Relic](https://newrelic.com/).

## Project website (if applicable)

https://newrelic.com/

## Context

Perhaps different views that embed different graphs based on use-case. A backend service will likely look at different graphs than a web app, for instance.

**Comment by timwheelercom** [comment]
@palmerj3 I've put up a PR for a basic New Relic plugin implementation that will display New Relic APM data: https://github.com/spotify/backstage/pull/1875

**Comment by iamEAP** [comment]
I'm thinking of hacking on / improving this plugin in the coming week, if anyone else is interested.  Here's my initial thoughts:

### What/Why
In order to expose the most functionality from New Relic without integrating with each of its constituent products piecemeal (e.g. APM, Browser, Infrastructure, Synthetics, Mobile, Logs, etc), it'd be better to integrate directly with their Insights product, which exposes data from all of their products through [a unified query interface](https://docs.newrelic.com/docs/insights/insights-api/get-data/query-insights-event-data-api).

This would put the burden of visualization on us, but there aren't really any better options for the time being, as New Relic only exposes charts as embeddable entities in their APM product. 

### Proposed Implementation
- [Integrate into the service catalogue](https://backstage.io/docs/plugins/integrating-plugin-into-service-catalog)
- Define how Component entities can be decorated with a list of Insight chart definitions, which could be rendered within a separate tab/view on the service catalogue.  Properties like: `NRQL Query`, `Chart Type`, etc.
- Render using [TrendLine](https://backstage.io/storybook/?path=/story/trendline--default), [Gauge](https://backstage.io/storybook/?path=/story/gauge--default) components from storybook (or simple text/tables), depending on the query/ chosen chart type.

---

Would love feedback on the proposal above.

**Comment by stefanalund** [comment]
https://github.com/spotify/backstage/tree/master/plugins/newrelic
